"""
GENERATED by scripts/sync-from-expo-hermes.sh from expo-hermes's
plugins/platforms/hermes_bridge/test_rpc.py — edit the source there, not here.

Unit tests for HermesBridgeAdapter RPC dispatch — cron write methods + dedup.

Run:
    PYTHONPATH=<repo-root> ~/.hermes/hermes-agent/venv/bin/python plugins/platforms/hermes_bridge/test_rpc.py
or with any Python ≥3.8 that has websockets + PyNaCl installed.
"""

import json
import os
import sys
import unittest
from unittest.mock import AsyncMock, MagicMock, patch

# Ensure repo root is on the path; testutil stubs heavy deps on import.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from testutil import make_adapter as _make_adapter
from hermes_bridge.adapter import _diff_new_pending, _project_session_messages
from hermes_bridge.local_api import (
    API_SERVER_PORT,
    discover_dashboard_ports,
)


class _NeverRaised(Exception):
    """Stand-in for psutil's exception classes in a MagicMock'd psutil — the
    real ones must be catchable types, and nothing in these tests raises them."""


def _rpc_payload(method, params=None, rpc_id="test-id-001"):
    return {
        "role": "rpc.request",
        "content": "",
        "rpc": {"id": rpc_id, "method": method, "params": params or {}},
    }


class TestCronWriteMethods(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.adapter = _make_adapter()

    async def test_sessions_active_returns_current_phone_thread_ids(self):
        self.adapter._thread_phone_session = {"gateway-a": "phone-a"}
        self.adapter._active_threads = {"gateway-a", "phone-b"}
        self.assertEqual(await self.adapter._rpc_sessions_active({}), {"active": ["phone-a", "phone-b"]})

    async def test_sessions_create_returns_a_fresh_phone_thread_id(self):
        first = await self.adapter._rpc_sessions_create({})
        second = await self.adapter._rpc_sessions_create({})
        self.assertRegex(first["id"], r"^\d{8}_\d{6}_[0-9a-f]{6}$")
        self.assertNotEqual(first["id"], second["id"])

    async def test_sessions_fork_validates_source_and_stores_projected_handoff(self):
        self.adapter._listed_bridge_sessions = AsyncMock(return_value=[
            {"id": "telegram-id", "source": "telegram", "title": "Original"},
        ])
        self.adapter._api.get = AsyncMock(return_value={"messages": [
            {"role": "user", "content": "question"},
            {"role": "assistant", "content": "answer"},
        ]})

        result = await self.adapter._rpc_sessions_fork({"id": "telegram-id"})

        self.assertRegex(result["id"], r"^\d{8}_\d{6}_[0-9a-f]{6}$")
        self.assertEqual(result["title"], "↪ Original")
        self.assertEqual(result["forked_from"], "telegram-id")
        self.assertIn("User: question", self.adapter._pending_handoffs[result["id"]])
        self.assertIn("Assistant: answer", self.adapter._pending_handoffs[result["id"]])

    async def test_sessions_fork_rejects_a_bridge_session(self):
        self.adapter._listed_bridge_sessions = AsyncMock(return_value=[
            {"id": "bridge-id", "source": "hermes_bridge", "title": "Phone chat"},
        ])

        with self.assertRaisesRegex(Exception, "session_not_forkable"):
            await self.adapter._rpc_sessions_fork({"id": "bridge-id"})

    def test_sessions_messages_projection_drops_scaffolding_and_folds_tool_reasoning(self):
        projected = _project_session_messages({"messages": [
            {"role": "user", "content": '[IMPORTANT: The user has invoked the "x" skill, indicating they want to follow its instructions. The full skill content is loaded below.]\nBODY\nThe user has provided the following instruction alongside the skill invocation: fix it'},
            {"role": "user", "content": "[System: model]", "display_kind": "model_switch"},
            {"role": "user", "content": "[System: untyped]"},
            {"role": "user", "content": "raw", "display_kind": "steer", "display_content": "own words"},
            {"role": "user", "content": "[OUT-OF-BAND USER MESSAGE — busy]\nplease check\n[/OUT-OF-BAND USER MESSAGE]", "display_kind": "internal_notification"},
            {"role": "user", "content": '[HANDOFF CONTEXT — from telegram session "title" (id)]\nOld context\n[/HANDOFF CONTEXT]\n\nnew words'},
            {"role": "assistant", "content": "", "finish_reason": "tool_calls", "reasoning": "thinking"},
            {"role": "assistant", "content": "answer", "reasoning": "visible reason"},
        ]})
        rows = projected["messages"]
        self.assertEqual([row["content"] for row in rows], ["/x — fix it", "own words", "please check", "new words", "answer"])
        self.assertIn("thinking", rows[-1]["reasoning"])

    async def _run(self, method, params=None, rpc_id="rid-1"):
        """Run _handle_rpc and return the first sealed WS send call's decoded payload."""
        sent_frames = []

        async def capture_send(frame):
            sent_frames.append(frame)

        self.adapter._ws.send = capture_send

        hermes_response = {"status": "ok"}
        with patch.object(self.adapter._api, "get", AsyncMock(return_value=[{"id": "job", "profile": "default"}])), patch.object(
            self.adapter._api, "post", AsyncMock(return_value=hermes_response)
        ) as mock_post:
            await self.adapter._handle_rpc(
                _rpc_payload(method, params, rpc_id=rpc_id)
            )
        return sent_frames, mock_post

    async def test_cron_pause_calls_correct_path(self):
        frames, mock_post = await self._run("cron.pause", {"id": "job-abc", "profile": "default"})
        mock_post.assert_called_once_with("/api/cron/jobs/job-abc/pause?profile=default")
        assert len(frames) == 1

    async def test_cron_resume_calls_correct_path(self):
        frames, mock_post = await self._run("cron.resume", {"id": "job-xyz", "profile": "default"})
        mock_post.assert_called_once_with("/api/cron/jobs/job-xyz/resume?profile=default")
        assert len(frames) == 1

    async def test_cron_trigger_calls_correct_path(self):
        frames, mock_post = await self._run("cron.trigger", {"id": "job-123", "profile": "default"})
        mock_post.assert_called_once_with("/api/cron/jobs/job-123/trigger?profile=default")
        assert len(frames) == 1

    async def test_cron_delete_calls_correct_path_and_method(self):
        """DELETE on the bare job resource (#46) — not a pause/resume/trigger-
        style POST to an action sub-path, since upstream's real route is
        `DELETE /api/cron/jobs/{id}` (hermes_cli/web_routers/cron.py)."""
        frames, mock_post = await self._run("cron.delete", {"id": "job-999", "profile": "default"})
        mock_post.assert_called_once_with("/api/cron/jobs/job-999?profile=default", method="DELETE")
        assert len(frames) == 1

    async def test_cron_action_requires_an_explicit_profile(self):
        frames, mock_post = await self._run("cron.pause", {"id": "job-abc"})
        mock_post.assert_not_called()
        assert len(frames) == 1

    async def test_cron_action_rejects_profile_fallback_to_another_owner(self):
        with patch.object(self.adapter._api, "get", AsyncMock(return_value=[{"id": "job", "profile": "default"}])), patch.object(
            self.adapter._api, "post", AsyncMock()
        ) as mock_post, patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as response:
            await self.adapter._handle_rpc(_rpc_payload("cron.pause", {"id": "job", "profile": "coder"}))
        mock_post.assert_not_awaited()
        self.assertEqual(response.await_args.kwargs["error"], "cron_owner_mismatch")

    async def test_cron_action_accepts_ownerless_job_from_profile_scoped_list(self):
        with patch.object(self.adapter._api, "get", AsyncMock(return_value=[{"id": "job-123"}])), patch.object(
            self.adapter._api, "post", AsyncMock(return_value={"status": "ok"})
        ) as mock_post:
            await self.adapter._rpc_cron_action({"id": "job-123", "profile": "coder"}, "trigger")
        mock_post.assert_awaited_once_with("/api/cron/jobs/job-123/trigger?profile=coder")

    async def test_missing_job_id_returns_error(self):
        sent_frames = []

        async def capture_send(frame):
            sent_frames.append(frame)

        self.adapter._ws.send = capture_send

        with patch.object(self.adapter._api, "post", AsyncMock()) as mock_post:
            await self.adapter._handle_rpc(_rpc_payload("cron.pause", {"id": ""}))

        mock_post.assert_not_called()
        # _send_rpc_response still sends a frame even on error
        assert len(sent_frames) == 1

    async def test_dedup_skips_duplicate_rpc_id(self):
        sent_frames = []

        async def capture_send(frame):
            sent_frames.append(frame)

        self.adapter._ws.send = capture_send

        with patch.object(
            self.adapter._api, "get", AsyncMock(return_value=[{"id": "job-1", "profile": "default"}])
        ), patch.object(
            self.adapter._api, "post", AsyncMock(return_value={"ok": True})
        ) as mock_post:
            # First call — should be processed
            await self.adapter._handle_rpc(
                _rpc_payload("cron.trigger", {"id": "job-1", "profile": "default"}, rpc_id="dup-id-001")
            )
            # Second call — same rpc.id — should be dropped
            await self.adapter._handle_rpc(
                _rpc_payload("cron.trigger", {"id": "job-1", "profile": "default"}, rpc_id="dup-id-001")
            )

        mock_post.assert_called_once()  # only fired once despite two calls
        assert len(sent_frames) == 1

    async def test_different_rpc_ids_both_processed(self):
        sent_frames = []

        async def capture_send(frame):
            sent_frames.append(frame)

        self.adapter._ws.send = capture_send

        with patch.object(
            self.adapter._api, "get", AsyncMock(return_value=[{"id": "job-1", "profile": "default"}])
        ), patch.object(
            self.adapter._api, "post", AsyncMock(return_value={"ok": True})
        ) as mock_post:
            await self.adapter._handle_rpc(
                _rpc_payload("cron.trigger", {"id": "job-1", "profile": "default"}, rpc_id="id-A")
            )
            await self.adapter._handle_rpc(
                _rpc_payload("cron.trigger", {"id": "job-1", "profile": "default"}, rpc_id="id-B")
            )

        assert mock_post.call_count == 2
        assert len(sent_frames) == 2


def _json_response(payload: dict):
    """Minimal stand-in for urlopen's context manager: .read() returns JSON bytes."""
    import io
    from contextlib import contextmanager

    class _Resp(io.BytesIO):
        def __enter__(self):
            return self

        def __exit__(self, *a):
            self.close()
            return False

    return _Resp(json.dumps(payload).encode())


def _http_error(status: int, detail: str):
    """Build a real urllib.error.HTTPError whose body is FastAPI's
    {"detail": "..."} shape, for testing _http_error_detail passthrough."""
    import io
    import urllib.error

    body = json.dumps({"detail": detail}).encode()
    return urllib.error.HTTPError(
        url="http://localhost:9119/api/cron/jobs",
        code=status,
        msg="Bad Request",
        hdrs=None,
        fp=io.BytesIO(body),
    )


class TestCronCreateEdit(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.adapter = _make_adapter()
        self.sent_frames = []

        async def capture_send(frame):
            self.sent_frames.append(frame)

        self.adapter._ws.send = capture_send

    async def test_create_missing_schedule_returns_error(self):
        with patch.object(self.adapter._api, "post", AsyncMock()) as mock_post:
            await self.adapter._handle_rpc(_rpc_payload("cron.create", {"prompt": "hello"}))
        mock_post.assert_not_called()
        assert len(self.sent_frames) == 1

    async def test_create_calls_correct_path_with_body(self):
        with patch.object(
            self.adapter._api, "post", AsyncMock(return_value={"id": "job-new"})
        ) as mock_post:
            await self.adapter._handle_rpc(
                _rpc_payload(
                    "cron.create",
                    {
                        "schedule": "every 2h",
                        "profile": "coder",
                        "context_from": ["self", "job-upstream"],
                        "prompt": "check server status",
                        "name": "Health check",
                        "deliver": "origin",
                        "skills": ["blogwatcher"],
                    },
                )
            )
        mock_post.assert_called_once_with(
            "/api/cron/jobs?profile=coder",
            body={
                "schedule": "every 2h",
                "context_from": ["self", "job-upstream"],
                "prompt": "check server status",
                "name": "Health check",
                "deliver": "origin",
                "skills": ["blogwatcher"],
            },
        )
        assert len(self.sent_frames) == 1

    async def test_create_without_continuity_does_not_send_context_from(self):
        with patch.object(self.adapter._api, "post", AsyncMock(return_value={"id": "new"})) as post:
            await self.adapter._handle_rpc(_rpc_payload(
                "cron.create", {"schedule": "every 1h", "profile": "default"}
            ))
        post.assert_called_once_with(
            "/api/cron/jobs?profile=default", body={"schedule": "every 1h"}
        )

    async def test_create_schedule_parse_error_surfaces_detail(self):
        """Hermes core's HTTP 400 {"detail": "..."} must reach the RPC caller
        as the actual message — not the generic hermes_api_unavailable the
        catch-all below would otherwise produce for any non-401 HTTPError."""
        error = _http_error(400, "Could not parse schedule: 'whenever'")
        with patch.object(
            self.adapter, "_send_rpc_response", AsyncMock()
        ) as mock_response, patch.object(self.adapter._api, "post", AsyncMock(side_effect=error)):
            await self.adapter._handle_rpc(
                _rpc_payload("cron.create", {"schedule": "whenever", "prompt": "x", "profile": "default"})
            )
        call_kwargs = mock_response.call_args.kwargs
        assert call_kwargs["ok"] is False
        assert "Could not parse schedule" in call_kwargs["error"]


    async def test_edit_missing_job_id_returns_error(self):
        with patch.object(self.adapter._api, "post", AsyncMock()) as mock_post:
            await self.adapter._handle_rpc(_rpc_payload("cron.edit", {"schedule": "1h"}))
        mock_post.assert_not_called()
        assert len(self.sent_frames) == 1

    async def test_edit_no_fields_returns_error(self):
        with patch.object(self.adapter._api, "post", AsyncMock()) as mock_post:
            await self.adapter._handle_rpc(_rpc_payload("cron.edit", {"id": "job-1"}))
        mock_post.assert_not_called()
        assert len(self.sent_frames) == 1

    async def test_edit_sends_partial_updates_wrapped(self):
        with patch.object(
            self.adapter._api, "get", AsyncMock(return_value=[{"id": "job-1", "profile": "coder"}])
        ), patch.object(
            self.adapter._api, "post", AsyncMock(return_value={"id": "job-1"})
        ) as mock_post:
            await self.adapter._handle_rpc(
                _rpc_payload("cron.edit", {"id": "job-1", "schedule": "every 1h", "profile": "coder", "context_from": ["self"]})
            )
        mock_post.assert_called_once_with(
            "/api/cron/jobs/job-1?profile=coder",
            body={"updates": {"schedule": "every 1h", "context_from": ["self"]}},
            method="PUT",
        )
        assert len(self.sent_frames) == 1

    async def test_edit_schedule_parse_error_surfaces_detail(self):
        error = _http_error(400, "Could not parse schedule: 'nonsense'")
        with patch.object(
            self.adapter._api, "get", AsyncMock(return_value=[{"id": "job-1", "profile": "default"}])
        ), patch.object(
            self.adapter, "_send_rpc_response", AsyncMock()
        ) as mock_response, patch.object(self.adapter._api, "post", AsyncMock(side_effect=error)):
            await self.adapter._handle_rpc(
                _rpc_payload("cron.edit", {"id": "job-1", "schedule": "nonsense", "profile": "default"})
            )
        call_kwargs = mock_response.call_args.kwargs
        assert call_kwargs["ok"] is False
        assert "Could not parse schedule" in call_kwargs["error"]


class TestCronOwnerReads(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.adapter = _make_adapter()

    async def test_list_reads_each_profile_and_keeps_duplicate_ids_separate(self):
        async def _get(path):
            if path == "/api/profiles":
                return {"profiles": [{"name": "default"}, {"name": "coder"}]}
            if path == "/api/cron/jobs?profile=default":
                return [{"id": "same-id", "profile": "default", "context_from": ["self"], "hermes_home": "/secret"}]
            if path == "/api/cron/jobs?profile=coder":
                return [{"id": "same-id", "profile": "coder", "context_from": ["job-x"], "hermes_home": "/secret"}]
            raise AssertionError(path)

        with patch.object(self.adapter._api, "get", _get):
            jobs = await self.adapter._rpc_cron_list({})
        assert {(job["id"], job["profile"]) for job in jobs} == {
            ("same-id", "default"), ("same-id", "coder")
        }
        assert next(job for job in jobs if job["profile"] == "default")["context_from"] == ["self"]
        assert "hermes_home" not in str(jobs)

    async def test_run_history_uses_explicit_profile(self):
        with patch.object(
            self.adapter._api, "get", AsyncMock(side_effect=[[{"id": "same-id", "profile": "coder"}], {"runs": []}])
        ) as get:
            await self.adapter._rpc_cron_runs({
                "job_id": "same-id", "profile": "coder", "limit": 10
            })
        self.assertEqual(get.await_args_list[-1].args[0],
            "/api/cron/jobs/same-id/runs?limit=10&profile=coder"
        )

    async def test_run_history_rejects_another_owner(self):
        with patch.object(
            self.adapter._api, "get", AsyncMock(return_value=[{"id": "same-id", "profile": "default"}])
        ) as get:
            with self.assertRaisesRegex(Exception, "cron_owner_mismatch"):
                await self.adapter._rpc_cron_runs({"job_id": "same-id", "profile": "coder"})
        get.assert_awaited_once()


class TestHermesRequestHttpError(unittest.IsolatedAsyncioTestCase):
    """_hermes_request must treat a non-401 HTTPError as authoritative: a live
    Hermes answered on that port. Probing further ports would bury the error
    under connection-refused noise (breaking detail passthrough) and replay a
    non-idempotent POST."""

    async def test_non_401_error_raises_immediately_without_probing_other_ports(self):
        import urllib.error

        adapter = _make_adapter()
        adapter._api._tokens = {9119: "cached-token"}
        adapter._api.port = None

        attempted_urls = []

        def fake_urlopen(req, timeout=None):
            attempted_urls.append(req.full_url)
            raise _http_error(400, "Could not parse schedule: 'whenever'")

        with patch.object(adapter._api, "ports_to_probe", return_value=[9119, 9120, 8642]), patch(
            "urllib.request.urlopen", side_effect=fake_urlopen
        ):
            with self.assertRaises(urllib.error.HTTPError) as ctx:
                await adapter._api.request("/api/cron/jobs", method="POST", body={"schedule": "whenever"})

        assert len(attempted_urls) == 1, f"expected single attempt, got {attempted_urls}"
        assert ctx.exception.code == 400
        # The answering port is the working port — cache it.
        assert adapter._api.port == 9119


class TestHermesRequestPortSelection(unittest.IsolatedAsyncioTestCase):
    """(#64) Port selection must not mistake the wrong service for the right one.

    The adapter probes candidate ports for the Hermes DASHBOARD REST API. A 404
    means something is listening that does not serve these routes -- the wrong
    service -- so probing must continue. Treating 404 as "a live Hermes
    answered" is what pinned the adapter to the api_server platform on 8642 and
    made every Agent-tab RPC fail with a 404 that looked like a real answer.
    """

    async def test_404_keeps_probing_and_does_not_pin_the_port(self):
        adapter = _make_adapter()
        adapter._api._tokens = {}
        adapter._api.port = None
        attempted = []

        def fake_urlopen(req, timeout=None):
            attempted.append(req.full_url)
            if ":9119" in req.full_url:
                raise _http_error(404, "Not Found")
            return _json_response({"ok": True, "port": 9120})

        with patch.object(adapter._api, "ports_to_probe", return_value=[9119, 9120]), patch.object(
            adapter._api, "token", AsyncMock(return_value="tok")
        ), patch("urllib.request.urlopen", side_effect=fake_urlopen):
            result = await adapter._api.request("/api/sessions")

        assert len(attempted) == 2, f"404 should not stop the probe: {attempted}"
        assert result["port"] == 9120
        assert adapter._api.port == 9120, "must pin the port that actually answered"

    async def test_404_on_a_cached_port_clears_the_cache(self):
        adapter = _make_adapter()
        adapter._api._tokens = {}
        adapter._api.port = 9119  # stale pin at the wrong service

        def fake_urlopen(req, timeout=None):
            raise _http_error(404, "Not Found")

        with patch.object(adapter._api, "ports_to_probe", return_value=[9119]), patch.object(
            adapter._api, "token", AsyncMock(return_value="tok")
        ), patch("urllib.request.urlopen", side_effect=fake_urlopen):
            with self.assertRaises(Exception):
                await adapter._api.request("/api/sessions")

        assert adapter._api.port is None, "a 404 must not leave the wrong port pinned"

    async def test_api_port_override_is_tried_first(self):
        """psutil discovery is the only thing that finds a --port 0 dashboard.
        When it comes up empty (no psutil, AccessDenied, an unfamiliar command
        line), a running dashboard still reads as hermes_offline with nothing
        the user can change — HERMES_BRIDGE_API_PORT is that escape hatch."""
        adapter = _make_adapter()
        adapter._api.port = 9120  # a stale pin must not outrank it

        with patch.dict(os.environ, {"HERMES_BRIDGE_API_PORT": "51234"}), patch(
            "hermes_bridge.local_api.discover_dashboard_ports",
            return_value=[],
        ):
            ports = adapter._api.ports_to_probe()

        assert ports[0] == 51234, f"the override must be probed first: {ports}"
        assert 9119 in ports, "the defaults stay as fallbacks"
        assert len(ports) == len(set(ports)), f"ports must be deduplicated: {ports}"

    async def test_both_local_services_stay_in_the_probe_list(self):
        """The adapter talks to two local services through one probe loop: the
        dashboard (/api/* routes, default 9119) and the api_server platform
        (/v1/approvals and the /v1/runs SSE, default 8642). Neither serves the
        other's routes, so both must stay probeable -- dropping 8642 would break
        approvals and runs. What must NOT happen is a 404 from one being read as
        "this is the working port", which is the bug this class covers."""
        adapter = _make_adapter()
        with patch(
            "hermes_bridge.local_api.discover_dashboard_ports",
            return_value=[],
        ):
            probe = adapter._api.ports_to_probe()
            dashboard_only = adapter._api.dashboard_candidates()

        assert probe[0] == 9119, "the dashboard default is tried first"
        assert API_SERVER_PORT in probe, "api_server's port serves the /v1/* routes"
        # The two orderings are the reason no `port == 8642` filter is needed
        # anywhere: a listener there must never read as "the Agent screen's API
        # is up", so `listening()`/`_ensure()` walk the dashboard list only.
        assert API_SERVER_PORT not in dashboard_only


class TestLocalApiAutostart(unittest.IsolatedAsyncioTestCase):
    """Hermes ships no autostart setting for the dashboard, and a hand-started
    one dies with its terminal — so LocalApi starts the headless backend
    itself, parented to this gateway, and keeps out of the way of an
    operator's own.
    """

    async def test_starts_the_local_api_when_nothing_serves_it(self):
        """Hermes has no autostart config for the dashboard, so a gateway-only
        install answered every Agent-tab RPC with hermes_offline. The adapter
        spawns the lean headless backend itself, parented to this gateway."""
        adapter = _make_adapter()

        with patch.object(adapter._api, "listening", return_value=None), patch(
            "hermes_bridge.local_api.subprocess.Popen"
        ) as popen:
            popen.return_value.pid = 4242
            popen.return_value.poll.return_value = None
            await adapter._api._ensure()

        argv, kwargs = popen.call_args[0][0], popen.call_args[1]
        assert argv[1:4] == ["-m", "hermes_cli.main", "serve"], f"lean surface only: {argv}"
        assert "9119" in argv, f"pin the port the probe list starts with: {argv}"
        # Hermes' own watchdog reaps the child when this gateway dies — that is
        # what makes a service file unnecessary.
        assert kwargs["env"]["HERMES_PARENT_PID"] == str(os.getpid())

    async def test_start_leaves_a_supervisor_that_stop_cancels(self):
        """The supervisor IS the fix for a crashed backend: _ensure used to run
        once from connect(), while relay reconnects go through _connect_ws, so
        nothing ever replaced a dead API for the gateway's lifetime."""
        adapter = _make_adapter()

        with patch.object(adapter._api, "listening", return_value=9119):
            await adapter._api.start()
            supervisor = adapter._api._supervisor
            assert supervisor is not None and not supervisor.done(), "no supervisor task"

            # Idempotent: a second start must not stack another task.
            await adapter._api.start()
            assert adapter._api._supervisor is supervisor

        await adapter._api.stop()
        assert supervisor.cancelled(), "stop must cancel the supervisor"
        assert adapter._api._supervisor is None

    async def test_supervisor_respawns_a_backend_that_died(self):
        adapter = _make_adapter()
        dead = MagicMock()
        dead.poll.return_value = 1  # exited
        adapter._api._proc = dead

        with patch.object(adapter._api, "listening", return_value=None), patch(
            "hermes_bridge.local_api.subprocess.Popen"
        ) as popen:
            popen.return_value.pid = 4243
            await adapter._api._ensure()

        popen.assert_called_once()
        assert adapter._api._proc is not dead, "the dead handle must be replaced"

    async def test_discovery_matches_the_subcommand_not_a_path_substring(self):
        """"serve" appears in plenty of filesystem paths; a false positive puts
        a wrong port ahead of the defaults in the probe order."""
        def proc(cmdline, port):
            p = MagicMock()
            p.info = {"pid": 1, "cmdline": cmdline}
            conn = MagicMock()
            conn.status = "LISTEN"
            conn.laddr.port = port
            p.net_connections.return_value = [conn]
            return p

        real = proc(["/opt/hermes/venv/bin/python", "-m", "hermes_cli.main", "serve"], 9131)
        decoy = proc(["/Users/x/servers/hermes-tools/bin/python", "worker.py"], 7777)
        psutil = MagicMock()
        psutil.process_iter.return_value = [decoy, real]
        psutil.NoSuchProcess = psutil.AccessDenied = _NeverRaised

        with patch.dict("sys.modules", {"psutil": psutil}):
            assert discover_dashboard_ports() == [9131]

    async def test_does_not_start_a_second_api_over_a_live_one(self):
        adapter = _make_adapter()

        with patch.object(adapter._api, "listening", return_value=9119), patch(
            "hermes_bridge.local_api.subprocess.Popen"
        ) as popen:
            await adapter._api._ensure()
        popen.assert_not_called()

        # Opting out must hold even when nothing is listening.
        with patch.dict(os.environ, {"HERMES_BRIDGE_START_API": "0"}), patch.object(
            adapter._api, "listening", return_value=None
        ), patch("hermes_bridge.local_api.subprocess.Popen") as popen:
            await adapter._api._ensure()
        popen.assert_not_called()

class TestHermesSessionTokenIsPerPort(unittest.IsolatedAsyncioTestCase):
    """(#64) The dashboard mints its session token per process
    (secrets.token_urlsafe(32) in hermes_cli/web_server.py), so a token scraped
    from one dashboard is invalid on another. The cache must be keyed by port --
    discover_dashboard_ports() deliberately returns several (main + per-profile).
    """

    async def test_token_cached_for_one_port_is_not_reused_for_another(self):
        adapter = _make_adapter()
        adapter._api._tokens = {9119: "token-for-9119"}
        scraped = []

        def fake_fetch(port):
            scraped.append(port)
            return f"token-for-{port}"

        with patch.object(adapter._api, "_fetch_session_token", side_effect=fake_fetch):
            same = await adapter._api.token(9119)
            other = await adapter._api.token(9120)

        assert same == "token-for-9119", "cached port must not re-scrape"
        assert scraped == [9120], f"only the uncached port should be scraped: {scraped}"
        assert other == "token-for-9120", "each port gets its own token"

    async def test_401_clears_only_the_failing_port_token(self):
        adapter = _make_adapter()
        adapter._api._tokens = {9119: "stale", 9120: "still-good"}
        adapter._api.port = None

        def fake_urlopen(req, timeout=None):
            if ":9119" in req.full_url:
                raise _http_error(401, "Unauthorized")
            return _json_response({"ok": True})

        with patch.object(adapter._api, "ports_to_probe", return_value=[9119, 9120]), patch.object(
            adapter._api, "_fetch_session_token", side_effect=lambda port: None
        ), patch("urllib.request.urlopen", side_effect=fake_urlopen):
            await adapter._api.request("/api/sessions")

        assert 9119 not in adapter._api._tokens, "failing port's token must be cleared"
        assert adapter._api._tokens.get(9120) == "still-good", (
            "a 401 on one port must not invalidate another port's token"
        )


class TestChatStop(unittest.IsolatedAsyncioTestCase):
    """chat.stop has no adapter-side interrupt logic — it synthesizes "/stop"
    and routes it through handle_message(), the same dispatch path every
    normal incoming message takes, so Hermes core's central /stop command
    handler (gateway/slash_commands.py) does the actual interrupt."""

    def setUp(self):
        self.adapter = _make_adapter()
        self.sent_frames = []

        async def capture_send(frame):
            self.sent_frames.append(frame)

        self.adapter._ws.send = capture_send

    async def test_stop_dispatches_slash_stop_via_handle_message(self):
        # build_source/handle_message are real BasePlatformAdapter methods
        # (never overridden by HermesBridgeAdapter) — patching the module-
        # level BasePlatformAdapter name doesn't rewire an already-defined
        # subclass's MRO, so they're stubbed per-instance here rather than
        # exercising the genuine Hermes-core implementation (which needs a
        # fully constructed adapter/session context this harness doesn't build).
        with patch.object(
            self.adapter, "build_source", return_value={"chat_id": "test-profile"}
        ), patch.object(self.adapter, "handle_message", AsyncMock()) as mock_handle:
            await self.adapter._handle_rpc(_rpc_payload("chat.stop", {}))

        mock_handle.assert_called_once()
        event = mock_handle.call_args.args[0]
        assert event.text == "/stop"
        assert len(self.sent_frames) == 1

    async def test_stop_stamps_profile_for_profile_thread(self):
        self.adapter._thread_core_profile = {"gateway-a": "work"}
        with patch.object(self.adapter, "build_source", return_value=MagicMock()), patch.object(self.adapter, "handle_message", AsyncMock()) as mock_handle:
            await self.adapter._rpc_chat_stop({"thread_id": "gateway-a"})
        self.assertEqual(mock_handle.call_args.args[0].source.profile, "work")

    async def test_stop_validates_and_stamps_payload_profile_without_thread_mapping(self):
        from hermes_bridge.bots_policy import ProfilesSnapshot
        with patch("hermes_bridge.adapter.fetch_profiles_snapshot", AsyncMock(return_value=ProfilesSnapshot({}, None, [{"name": "work"}]))), patch.dict(sys.modules, {"hermes_cli.gateway_multiplex_served": MagicMock(recorded_served_profiles=MagicMock(return_value=["work"]))}), patch.object(self.adapter, "build_source", return_value=MagicMock()), patch.object(self.adapter, "handle_message", AsyncMock()) as mock_handle:
            await self.adapter._rpc_chat_stop({"thread_id": "gateway-b", "core_profile": "work"})
        self.assertEqual(mock_handle.call_args.args[0].source.profile, "work")

    async def test_stop_thread_mapping_wins_over_payload_profile(self):
        self.adapter._thread_core_profile = {"gateway-a": "work"}
        with patch.object(self.adapter, "build_source", return_value=MagicMock()), patch.object(self.adapter, "handle_message", AsyncMock()) as mock_handle:
            await self.adapter._rpc_chat_stop({"thread_id": "gateway-a", "core_profile": "other"})
        self.assertEqual(mock_handle.call_args.args[0].source.profile, "work")

    async def test_stop_acks_even_with_no_active_turn(self):
        """_handle_stop_command is documented safe to call with nothing
        running — handle_message() itself must not raise either way."""
        with patch.object(
            self.adapter, "build_source", return_value={"chat_id": "test-profile"}
        ), patch.object(self.adapter, "handle_message", AsyncMock()), patch.object(
            self.adapter, "_send_rpc_response", AsyncMock()
        ) as mock_response:
            await self.adapter._handle_rpc(_rpc_payload("chat.stop", {}))

        call_kwargs = mock_response.call_args.kwargs
        assert call_kwargs["ok"] is True
        assert call_kwargs["data"] == {"stopped": True}


class TestWriteApprovalRpc(unittest.IsolatedAsyncioTestCase):
    """memory.*/skills.* write-approval RPCs (PRD_Features.md §2.7).

    These call tools.write_approval/tools.memory_tool/tools.skill_manager_tool
    directly rather than proxying to a REST endpoint — Hermes core has no HTTP
    surface for staged writes (confirmed: no matching route in
    gateway/platforms/api_server.py or hermes_cli/web_server.py). The gateway's
    own /memory and /skills slash-command handlers call these same functions
    in-process (gateway/slash_commands.py), which is what this adapter mirrors.
    """

    def setUp(self):
        self.adapter = _make_adapter()
        self.sent_frames = []

        async def capture_send(frame):
            self.sent_frames.append(frame)

        self.adapter._ws.send = capture_send

    async def test_memory_pending_lists_records(self):
        records = [
            {
                "id": "m1",
                "subsystem": "memory",
                "summary": "likes tea",
                "origin": "foreground",
                "created_at": 111.0,
                "payload": {"content": "likes tea"},
            }
        ]
        with patch("tools.write_approval.list_pending", return_value=records):
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("memory.pending"))
        data = mock_response.call_args.kwargs["data"]
        assert data == [
            {"id": "m1", "summary": "likes tea", "origin": "foreground", "created_at": 111.0, "content": "likes tea"}
        ]

    async def test_pending_summary_omits_skill_content(self):
        """Skill payload content must not leak into the pending list — only
        memory (small, ~200 char entries) gets inline content; skills fetch
        full content on demand via skills.diff."""
        records = [
            {
                "id": "s1",
                "subsystem": "skills",
                "summary": "gist",
                "origin": "foreground",
                "created_at": 1.0,
                "payload": {"content": "huge skill body"},
            }
        ]
        with patch("tools.write_approval.list_pending", return_value=records):
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("skills.pending"))
        data = mock_response.call_args.kwargs["data"]
        assert data[0]["content"] is None
        assert "huge skill body" not in json.dumps(data)

    async def test_memory_approve_applies_and_discards(self):
        rec = {"id": "m1", "subsystem": "memory", "payload": {"action": "add", "target": "user", "content": "x"}}
        with patch("tools.write_approval.get_pending", return_value=rec), patch(
            "tools.write_approval.discard_pending", return_value=True
        ) as mock_discard, patch(
            "tools.memory_tool.load_on_disk_store", return_value=MagicMock()
        ), patch(
            "tools.memory_tool.apply_memory_pending", return_value={"success": True}
        ) as mock_apply:
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("memory.approve", {"id": "m1"}))
        mock_apply.assert_called_once()
        mock_discard.assert_called_once_with("memory", "m1")
        assert mock_response.call_args.kwargs["ok"] is True

    async def test_memory_approve_failure_does_not_discard(self):
        """A failed replay (e.g. store write error) must NOT discard the
        pending record — otherwise the staged write is lost with nothing
        ever applied."""
        rec = {"id": "m1", "subsystem": "memory", "payload": {"action": "add"}}
        with patch("tools.write_approval.get_pending", return_value=rec), patch(
            "tools.write_approval.discard_pending"
        ) as mock_discard, patch(
            "tools.memory_tool.load_on_disk_store", return_value=MagicMock()
        ), patch(
            "tools.memory_tool.apply_memory_pending", return_value={"success": False, "error": "boom"}
        ):
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("memory.approve", {"id": "m1"}))
        mock_discard.assert_not_called()
        call_kwargs = mock_response.call_args.kwargs
        assert call_kwargs["ok"] is False
        assert "boom" in call_kwargs["error"]

    async def test_memory_approve_missing_pending_errors(self):
        with patch("tools.write_approval.get_pending", return_value=None):
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("memory.approve", {"id": "nope"}))
        call_kwargs = mock_response.call_args.kwargs
        assert call_kwargs["ok"] is False
        assert call_kwargs["error"] == "pending_not_found"

    async def test_memory_reject_discards(self):
        with patch("tools.write_approval.discard_pending", return_value=True) as mock_discard:
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("memory.reject", {"id": "m1"}))
        mock_discard.assert_called_once_with("memory", "m1")
        assert mock_response.call_args.kwargs["ok"] is True

    async def test_memory_reject_missing_pending_errors(self):
        with patch("tools.write_approval.discard_pending", return_value=False):
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("memory.reject", {"id": "nope"}))
        assert mock_response.call_args.kwargs["ok"] is False

    async def test_skills_approve_applies_and_discards(self):
        rec = {"id": "s1", "subsystem": "skills", "payload": {"action": "create", "name": "foo"}}
        with patch("tools.write_approval.get_pending", return_value=rec), patch(
            "tools.write_approval.discard_pending", return_value=True
        ) as mock_discard, patch(
            "tools.skill_manager_tool.apply_skill_pending",
            return_value=json.dumps({"success": True}),
        ) as mock_apply:
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("skills.approve", {"id": "s1"}))
        mock_apply.assert_called_once()
        mock_discard.assert_called_once_with("skills", "s1")
        assert mock_response.call_args.kwargs["ok"] is True

    async def test_skills_approve_failure_does_not_discard(self):
        rec = {"id": "s1", "subsystem": "skills", "payload": {"action": "create", "name": "foo"}}
        with patch("tools.write_approval.get_pending", return_value=rec), patch(
            "tools.write_approval.discard_pending"
        ) as mock_discard, patch(
            "tools.skill_manager_tool.apply_skill_pending",
            return_value=json.dumps({"success": False, "error": "name exists"}),
        ):
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("skills.approve", {"id": "s1"}))
        mock_discard.assert_not_called()
        call_kwargs = mock_response.call_args.kwargs
        assert call_kwargs["ok"] is False
        assert "name exists" in call_kwargs["error"]

    async def test_skills_reject_discards(self):
        with patch("tools.write_approval.discard_pending", return_value=True) as mock_discard:
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("skills.reject", {"id": "s1"}))
        mock_discard.assert_called_once_with("skills", "s1")
        assert mock_response.call_args.kwargs["ok"] is True

    async def test_skills_diff_returns_diff_text(self):
        rec = {"id": "s1", "subsystem": "skills", "payload": {"action": "create", "name": "foo", "content": "# Foo"}}
        with patch("tools.write_approval.get_pending", return_value=rec), patch(
            "tools.write_approval.skill_pending_diff", return_value="# Foo"
        ) as mock_diff:
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("skills.diff", {"id": "s1"}))
        mock_diff.assert_called_once_with(rec)
        assert mock_response.call_args.kwargs["data"] == {"diff": "# Foo"}

    async def test_skills_diff_missing_pending_errors(self):
        with patch("tools.write_approval.get_pending", return_value=None):
            with patch.object(self.adapter, "_send_rpc_response", AsyncMock()) as mock_response:
                await self.adapter._handle_rpc(_rpc_payload("skills.diff", {"id": "nope"}))
        assert mock_response.call_args.kwargs["ok"] is False


class TestDiffNewPending(unittest.TestCase):
    """_diff_new_pending is the one genuinely novel piece of
    _poll_pending_writes (PRD_Features.md §2.7) — a plain sync function so it
    doesn't need an event loop to test."""

    def test_first_call_returns_everything_and_seeds(self):
        seen: set = set()
        rec = {"id": "m1"}
        new = _diff_new_pending([rec], "memory", seen)
        assert new == [rec]
        assert ("memory", "m1") in seen

    def test_second_call_with_same_record_returns_nothing(self):
        seen: set = set()
        rec = {"id": "m1"}
        _diff_new_pending([rec], "memory", seen)
        new = _diff_new_pending([rec], "memory", seen)
        assert new == []

    def test_second_call_with_additional_record_returns_only_the_new_one(self):
        seen: set = set()
        rec1 = {"id": "m1"}
        rec2 = {"id": "m2"}
        _diff_new_pending([rec1], "memory", seen)
        new = _diff_new_pending([rec1, rec2], "memory", seen)
        assert new == [rec2]

    def test_same_id_different_subsystem_is_distinct(self):
        seen: set = set()
        _diff_new_pending([{"id": "x"}], "memory", seen)
        new = _diff_new_pending([{"id": "x"}], "skills", seen)
        assert new == [{"id": "x"}]


class TestPollPendingWrites(unittest.IsolatedAsyncioTestCase):
    """The first successful tick must establish a baseline (no pushes) rather
    than treating every already-pending write as new — otherwise a failed
    startup seed would cause a push burst on the recovery tick."""

    def setUp(self):
        self.adapter = _make_adapter()

    async def _run_two_ticks(self, fake_list_pending):
        sleeps = {"n": 0}

        async def fake_sleep(_seconds):
            sleeps["n"] += 1
            if sleeps["n"] >= 2:
                self.adapter._should_run = False

        self.adapter._should_run = True
        with patch("tools.write_approval.list_pending", side_effect=fake_list_pending), patch.object(
            self.adapter, "_send_lifecycle_event", AsyncMock()
        ) as mock_push, patch("asyncio.sleep", side_effect=fake_sleep):
            await self.adapter._poll_pending_writes()
        return mock_push

    async def test_first_tick_seeds_without_firing_then_detects_new_write(self):
        rec1 = {"id": "m1", "subsystem": "memory", "summary": "old"}
        rec2 = {"id": "m2", "subsystem": "memory", "summary": "brand new"}
        calls = {"n": 0}

        def fake_list_pending(subsystem):
            if subsystem != "memory":
                return []
            calls["n"] += 1
            return [rec1] if calls["n"] == 1 else [rec1, rec2]

        mock_push = await self._run_two_ticks(fake_list_pending)

        # rec1 was already pending on the very first tick — must never fire.
        # rec2 only appears on the second tick — must fire exactly once.
        assert mock_push.call_count == 1
        # (#44) the summary must NOT ride along in the lifecycle event — the
        # relay renders a generic template, so this call carries only
        # structural routing metadata (event_type + screen/tab/subsystem),
        # never message content. Do not "fix" this back to asserting the
        # summary is present — that was the plaintext leak #44 closed.
        assert mock_push.call_args.args[0] == "write.staged"
        data = mock_push.call_args.kwargs["data"]
        assert "brand new" not in json.dumps(data)
        assert data == {"screen": "agent", "tab": "approvals", "subsystem": "memory"}

    async def test_seed_failure_does_not_cause_burst_on_recovery(self):
        """A transient error on the very first list_pending call must not
        leave `seen` empty in a way that makes the NEXT (successful) tick
        treat every already-pending write as new."""
        rec1 = {"id": "m1", "subsystem": "memory", "summary": "old"}
        calls = {"n": 0}

        def fake_list_pending(subsystem):
            if subsystem != "memory":
                return []
            calls["n"] += 1
            if calls["n"] == 1:
                raise OSError("transient fs error")
            return [rec1]

        mock_push = await self._run_two_ticks(fake_list_pending)
        mock_push.assert_not_called()


class TestSessionHistoryPagination(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.adapter = _make_adapter()

    async def test_messages_passes_profile_to_both_rest_calls(self):
        with patch.object(self.adapter, "_resolve_core_profile", AsyncMock(return_value="work")), patch.object(
            self.adapter._api, "get", AsyncMock(side_effect=[{"sessions": [{"id": "s"}]}, {"messages": [], "pagination": {"returned": 0}}])
        ) as mock_get:
            await self.adapter._rpc_sessions_messages({"id": "s", "core_profile": "work", "limit": 20})
        self.assertEqual([call.args[0] for call in mock_get.await_args_list], [
            "/api/sessions?limit=100&profile=work",
            "/api/sessions/s/messages?limit=200&offset=0&order=latest&profile=work",
        ])

    async def test_history_page_resolves_profile_once(self):
        with patch.object(self.adapter, "_resolve_core_profile", AsyncMock(return_value="work")) as resolve, patch.object(
            self.adapter._api, "get", AsyncMock(side_effect=[{"sessions": [{"id": "s"}]}, {"messages": [], "pagination": {"returned": 0}}])
        ):
            await self.adapter._rpc_sessions_messages({"id": "s", "core_profile": "work", "limit": 20})
        resolve.assert_awaited_once_with("work")

    async def test_messages_rejects_invalid_profile(self):
        with patch.object(self.adapter, "_resolve_core_profile", AsyncMock(side_effect=Exception("profile_not_served"))):
            with self.assertRaisesRegex(Exception, "profile_not_served"):
                await self.adapter._rpc_sessions_messages({"id": "s", "core_profile": "missing"})

    async def test_messages_without_profile_keeps_existing_paths(self):
        with patch.object(self.adapter._api, "get", AsyncMock(return_value={"messages": []})) as mock_get:
            await self.adapter._rpc_sessions_messages({"id": "s"})
        self.assertEqual([call.args[0] for call in mock_get.await_args_list], [
            "/api/sessions?limit=100", "/api/sessions/s/messages"
        ])

    async def test_list_and_delete_are_profile_scoped(self):
        with patch.object(self.adapter, "_resolve_core_profile", AsyncMock(return_value="work")), patch.object(
            self.adapter._api, "get", AsyncMock(return_value={"sessions": []})
        ) as mock_get:
            await self.adapter._rpc_sessions_list({"core_profile": "work"})
        mock_get.assert_awaited_once_with("/api/sessions?limit=100&profile=work")
        with patch.object(self.adapter, "_resolve_core_profile", AsyncMock(return_value="work")), patch.object(
            self.adapter._api, "get", AsyncMock(return_value={"sessions": [{"id": "s"}]})
        ), patch.object(self.adapter._api, "request", AsyncMock()) as mock_request:
            await self.adapter._rpc_sessions_delete({"id": "s", "core_profile": "work"})
        mock_request.assert_awaited_once_with("/api/sessions/s?profile=work", method="DELETE")

    async def test_messages_forwards_latest_page_parameters(self):
        response = {"messages": [], "pagination": {"returned": 0}}
        with patch.object(
            self.adapter._api, "get", AsyncMock(return_value=response)
        ) as mock_get:
            result = await self.adapter._rpc_sessions_messages(
                {"id": "session/one", "limit": 20, "offset": 40, "order": "latest"}
            )

        self.assertEqual(
            result,
            {
                "messages": [],
                "pagination": {"returned": 0, "limit": 20, "offset": 40, "order": "latest"},
            },
        )
        self.assertEqual(
            [call.args for call in mock_get.await_args_list],
            [
                ("/api/sessions?limit=100",),
                ("/api/sessions/session%2Fone/messages?limit=200&offset=40&order=latest",),
            ],
        )

    async def test_messages_page_reports_raw_rows_consumed_for_tool_heavy_turns(self):
        # 30 raw rows of which only two are visible: the phone must get both
        # bubbles and advance its offset by the 30 raw rows read.
        raw = [{"id": i, "role": "tool", "content": "{}"} for i in range(27)]
        raw += [
            {
                "id": 99,
                "role": "assistant",
                "content": "[PRIOR CONTEXT — for reference only; not a new message]\nsummary",
                "finish_reason": "tool_calls",
                "display_kind": "hidden",
                "_compressed_summary": True,
            },
            {"id": 100, "role": "user", "content": "question"},
            {"id": 101, "role": "assistant", "content": "answer", "finish_reason": "stop"},
        ]
        response = {
            "messages": raw,
            "pagination": {"limit": 200, "offset": 0, "order": "latest", "returned": 30},
        }
        with patch.object(self.adapter._api, "get", AsyncMock(return_value=response)):
            result = await self.adapter._rpc_sessions_messages(
                {"id": "s", "limit": 20, "offset": 0, "order": "latest"}
            )
        self.assertEqual([m["content"] for m in result["messages"]], ["question", "answer"])
        self.assertEqual(
            result["pagination"], {"limit": 20, "offset": 0, "order": "latest", "returned": 30}
        )

    async def test_messages_without_page_parameters_preserves_legacy_path(self):
        with patch.object(
            self.adapter._api, "get", AsyncMock(return_value={"messages": []})
        ) as mock_get:
            await self.adapter._rpc_sessions_messages({"id": "session-one"})

        self.assertEqual(
            [call.args for call in mock_get.await_args_list],
            [
                ("/api/sessions?limit=100",),
                ("/api/sessions/session-one/messages",),
            ],
        )

    async def test_messages_rejects_invalid_page_parameters(self):
        with self.assertRaisesRegex(Exception, "invalid_history_page"):
            await self.adapter._rpc_sessions_messages(
                {"id": "session-one", "limit": 501, "offset": 0, "order": "latest"}
            )


class TestSessionSearch(unittest.IsolatedAsyncioTestCase):
    async def test_search_quotes_query_parameters(self):
        adapter = _make_adapter()
        response = {"results": []}
        with patch.object(adapter._api, "get", AsyncMock(return_value=response)) as mock_get:
            result = await adapter._rpc_sessions_search({"q": "release & notes", "limit": 20})

        self.assertEqual(result, response)
        mock_get.assert_awaited_once_with(
            "/api/sessions/search?q=release+%26+notes&limit=20"
        )


if __name__ == "__main__":
    unittest.main()
