"""pair.py end-to-end against a stub relay: provision, re-pair, interpreter selection.
GENERATED by scripts/sync-from-expo-hermes.sh from expo-hermes's
plugins/platforms/hermes_bridge/test_pair.py — edit the source there, not here.


Runs the real script logic over a real HTTP server in a throwaway
HERMES_HOME — the two branches (fresh provision vs existing profile) differ
only by what is already in .env, which is exactly the state a mocked test
would have to fake.
"""

import json
import os
import socket
import subprocess
import sys
import tempfile
import threading
import unittest
from contextlib import redirect_stdout
from io import StringIO
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from typing import Optional
from unittest.mock import patch

import hermes_bridge.pair as pair

REQUESTS: list = []


class _StubRelay(BaseHTTPRequestHandler):
    def do_POST(self):  # noqa: N802 — BaseHTTPRequestHandler's naming
        body = json.loads(self.rfile.read(int(self.headers["Content-Length"])) or "{}")
        REQUESTS.append(body)
        if body.get("profile_id"):
            payload = {"profile_id": body["profile_id"], "token": "tok_repair"}
        else:
            payload = {
                "profile_id": "profile_ss_abc123",
                "api_key": "hb_secret",
                "token": "tok_fresh",
                "expires_at": "2026-01-01T00:00:00.000Z",
            }
        raw = json.dumps(payload).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def log_message(self, *_args):
        pass


class PairScriptTest(unittest.TestCase):
    def setUp(self):
        REQUESTS.clear()
        self.server = HTTPServer(("127.0.0.1", 0), _StubRelay)
        threading.Thread(target=self.server.serve_forever, daemon=True).start()
        self.addCleanup(self.server.shutdown)

        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.home = Path(self.tmp.name)
        (self.home / ".env").write_text("EXISTING=1\n")

        relay = f"http://127.0.0.1:{self.server.server_port}"
        self.env = patch.dict(os.environ, {"HERMES_HOME": str(self.home)})
        self.env.start()
        self.addCleanup(self.env.stop)
        # No tty in the test runner, so pair.py never prompts; seed the relay
        # the same way an existing install would.
        self.relay_ws = relay.replace("http:", "ws:")
        self.default_relay = patch.object(pair, "DEFAULT_RELAY", relay)
        self.default_relay.start()
        self.addCleanup(self.default_relay.stop)

    def _run(self):
        with patch.object(sys.stdin, "isatty", return_value=False):
            pair.main()

    def test_first_run_provisions_and_writes_credentials(self):
        self._run()

        env = pair.read_env(self.home / ".env")
        self.assertEqual(env["HERMES_BRIDGE_PROFILE_ID"], "profile_ss_abc123")
        self.assertEqual(env["HERMES_BRIDGE_API_KEY"], "hb_secret")
        self.assertEqual(env["HERMES_BRIDGE_RELAY_URL"], self.relay_ws)
        self.assertEqual(REQUESTS, [{}], "fresh install must not send a profile_id")

        psk = self.home / "psk"
        self.assertEqual(len(psk.read_bytes()), 32)
        self.assertEqual(psk.stat().st_mode & 0o777, 0o600)
        self.assertIn("EXISTING=1", (self.home / ".env").read_text())

    def test_authorizes_the_adapter_sender_with_hermes(self):
        """Without this, Hermes default-denies the phone's first message and
        answers with a pairing code instead of a reply."""
        self._run()

        env = pair.read_env(self.home / ".env")
        self.assertEqual(env["HERMES_BRIDGE_ALLOWED_USERS"], "mobile")

        # Re-running must not duplicate or clobber the entry.
        self._run()
        self.assertEqual(
            (self.home / ".env").read_text().count("HERMES_BRIDGE_ALLOWED_USERS"), 1
        )

    def test_sets_the_home_channel_to_the_profile_chat(self):
        """Unset, Hermes nags on the first message and cron has no target."""
        self._run()

        env = pair.read_env(self.home / ".env")
        self.assertEqual(env["HERMES_BRIDGE_HOME_CHANNEL"], "profile_ss_abc123")

        self._run()
        self.assertEqual(
            (self.home / ".env").read_text().count("HERMES_BRIDGE_HOME_CHANNEL"), 1
        )

    def test_leaves_an_operator_set_home_channel_alone(self):
        (self.home / ".env").write_text("HERMES_BRIDGE_HOME_CHANNEL=somewhere-else\n")

        self._run()

        env = pair.read_env(self.home / ".env")
        self.assertEqual(env["HERMES_BRIDGE_HOME_CHANNEL"], "somewhere-else")

    def test_leaves_an_operator_set_allowlist_alone(self):
        (self.home / ".env").write_text("HERMES_BRIDGE_ALLOWED_USERS=mobile,someone\n")

        self._run()

        env = pair.read_env(self.home / ".env")
        self.assertEqual(env["HERMES_BRIDGE_ALLOWED_USERS"], "mobile,someone")

    def test_check_flag_reports_without_minting_an_invite(self):
        """`--check` is the diagnose-an-existing-install path: no relay call."""
        with patch.object(sys, "argv", ["pair.py", "--check"]):
            with self.assertRaises(SystemExit) as caught:
                self._run()

        self.assertEqual(caught.exception.code, 1, "no allowlist yet — should fail")
        self.assertEqual(REQUESTS, [], "--check must not touch the relay")
        self.assertEqual((self.home / ".env").read_text(), "EXISTING=1\n")
        self.assertFalse((self.home / "psk").exists())

    def test_readiness_fails_when_the_plugin_is_not_enabled(self):
        (self.home / "config.yaml").write_text("plugins:\n  enabled:\n    - something_else\n")
        self._run()  # pairs, and writes the allowlist

        def enablement_status():
            env = pair.read_env(self.home / ".env")
            return next(
                (status for status, label, _ in pair.readiness_report(self.home, env)
                 if "enabl" in label),
                None,
            )

        self.assertEqual(enablement_status(), pair.FAIL)

        (self.home / "config.yaml").write_text("plugins:\n  enabled:\n    - hermes_bridge\n")
        self.assertEqual(enablement_status(), pair.OK)

        # The inline-list form, and a legacy nested key, both count.
        (self.home / "config.yaml").write_text("plugins:\n  enabled: [other, hermes_bridge]\n")
        self.assertEqual(enablement_status(), pair.OK)
        (self.home / "config.yaml").write_text(
            "plugins:\n  enabled:\n    - platforms/hermes_bridge\n"
        )
        self.assertEqual(enablement_status(), pair.OK)

        # No config at all is "unknown", never a false alarm.
        (self.home / "config.yaml").unlink()
        self.assertIsNone(pair._plugin_enabled(self.home))

    def _clear_reexec_flag(self):
        os.environ.pop(pair._REEXEC_FLAG, None)

    def _symlink_legacy_python(self) -> Path:
        """A venv interpreter that is only a symlink to this process's binary.

        Resolving both paths yields the same file. That must not count as
        "already running in the dependency environment."
        """
        bin_dir = self.home / "hermes-agent" / "venv" / "bin"
        bin_dir.mkdir(parents=True)
        python = bin_dir / "python"
        python.symlink_to(sys.executable)
        return python

    def _write_launcher(self, runtime: Path, *, import_root: Optional[Path] = None, fail: bool = False) -> Path:
        bin_dir = self.home / "hermes-agent" / ".hermes" / "bin"
        bin_dir.mkdir(parents=True)
        launcher = bin_dir / "hermes"
        if fail:
            launcher.write_text("#!/bin/sh\nexit 1\n")
            launcher.chmod(0o755)
            return launcher
        root = import_root or (self.home / "hermes-agent")
        hits = self.home / "launcher-hits"
        body = "\n".join([
            "#!/usr/bin/env python3",
            "import json, sys",
            "from pathlib import Path",
            f"hit = Path({str(hits)!r})",
            'hit.write_text((hit.read_text() if hit.exists() else "") + "1")',
            'if "--print-runtime-command" not in sys.argv:',
            "    raise SystemExit(1)",
            'args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []',
            "code = (",
            '    "import os, sys, runpy; "',
            '    "os.environ.pop(\'PYTHONHOME\', None); "',
            '    "os.environ.pop(\'PYTHONPATH\', None); "',
            '    "os.environ.pop(\'VIRTUAL_ENV\', None); "',
            f'    "sys.path.insert(0, {str(root)!r}); "',
            '    "os.environ[\'HERMES_HOME\'] = os.environ.get(\'HERMES_HOME\') or \'\'; "',
            '    "import hermes_bootstrap; "',
            '    "runpy.run_module(\'hermes_cli.main\', run_name=\'__main__\', alter_sys=True)"',
            ")",
            f"print(json.dumps([{str(runtime)!r}, \"-I\", \"-c\", code, *args]))",
            "",
        ])
        launcher.write_text(body)
        launcher.chmod(0o755)
        return launcher

    def _exec_with_check(self):
        os.environ.pop(pair._REEXEC_FLAG, None)
        with patch.object(sys, "argv", ["pair.py", "--check"]):
            with patch.object(pair.os, "execv") as execv:
                with self.assertRaises(SystemExit) as caught:
                    self._run()
        return caught.exception.code, execv

    def test_prefers_the_published_launcher_over_a_resolved_legacy_binary(self):
        """Modern installs are selected by the launcher, even when the legacy
        venv python and the managed command resolve to this same binary."""
        legacy = self._symlink_legacy_python()
        runtime = self.home / "managed-python"
        runtime.symlink_to(sys.executable)
        self._write_launcher(runtime)

        code, execv = self._exec_with_check()

        self.assertEqual(code, 1)
        execv.assert_called_once()
        argv = execv.call_args[0][1]
        self.assertEqual(argv[0], str(runtime))
        self.assertNotEqual(argv[0], str(runtime.resolve()))
        self.assertNotEqual(argv[0], str(legacy))
        self.assertEqual(runtime.resolve(), legacy.resolve())
        self.assertIn("--check", argv)
        bootstrap = argv[argv.index("-c") + 1]
        self.assertIn("import hermes_bootstrap;", bootstrap)
        self.assertIn("os.environ.get('HERMES_HOME')", bootstrap)
        self.assertIn("runpy.run_path", bootstrap)
        self.assertNotIn("hermes_cli.main", bootstrap)
        self.assertNotIn("environments", " ".join(argv))
        self.assertEqual(os.environ["HERMES_HOME"], str(self.home))
        self.assertEqual((self.home / ".env").read_text(), "EXISTING=1\n")
        self.assertFalse((self.home / "psk").exists())
        self.assertEqual(REQUESTS, [])

    def test_legacy_venv_fallback_does_not_follow_symlinks(self):
        venv_python = self._symlink_legacy_python()

        _code, execv = self._exec_with_check()

        argv = execv.call_args[0][1]
        self.assertEqual(argv[0], str(venv_python))
        self.assertNotEqual(argv[0], str(venv_python.resolve()))
        self.assertEqual(argv[1], os.path.abspath(pair.__file__))
        self.assertIn("--check", argv)
        self.assertEqual(os.environ["HERMES_HOME"], str(self.home))

    def test_legacy_venv_fallback_when_the_launcher_cannot_print_a_runtime(self):
        venv_python = self._symlink_legacy_python()
        self._write_launcher(self.home / "unused-python", fail=True)

        _code, execv = self._exec_with_check()

        self.assertEqual(execv.call_args[0][1][0], str(venv_python))

    def test_reexec_flag_prevents_a_relaunch_loop(self):
        self._symlink_legacy_python()
        self._write_launcher(self.home / "managed-python")
        os.environ[pair._REEXEC_FLAG] = "1"

        with patch.object(sys, "argv", ["pair.py", "--check"]):
            with patch.object(pair.os, "execv") as execv:
                with self.assertRaises(SystemExit):
                    self._run()

        execv.assert_not_called()
        self.assertFalse((self.home / "launcher-hits").exists())

    def test_managed_environment_supplies_qrcode_and_check_writes_nothing(self):
        """The relaunch actually runs. qrcode exists only on the managed path
        the bootstrap inserts, and --check still does not provision or write
        credentials."""
        managed = self.home / "managed-site"
        managed.mkdir()
        (managed / "hermes_bootstrap.py").write_text("# selected environment, no relaunch\n")
        (managed / "qrcode.py").write_text(
            "import os\n"
            "from pathlib import Path\n"
            "marker = os.environ.get('HERMES_BRIDGE_QRCODE_MARKER')\n"
            "if marker:\n"
            "    Path(marker).write_text('managed\\n', encoding='utf-8')\n"
        )
        runtime = self.home / "managed-python"
        runtime.symlink_to(sys.executable)
        self._write_launcher(runtime, import_root=managed)
        marker = self.home / "qrcode-marker"
        env = os.environ.copy()
        env["HERMES_HOME"] = str(self.home)
        env["HERMES_BRIDGE_QRCODE_MARKER"] = str(marker)
        env.pop(pair._REEXEC_FLAG, None)

        completed = subprocess.run(
            [sys.executable, os.path.abspath(pair.__file__), "--check"],
            env=env,
            cwd=str(self.home),
            capture_output=True,
            text=True,
            timeout=20,
            stdin=subprocess.DEVNULL,
            check=False,
        )

        detail = f"rc={completed.returncode}\nSTDOUT:\n{completed.stdout}\nSTDERR:\n{completed.stderr}"
        self.assertEqual(marker.read_text(encoding="utf-8") if marker.exists() else "", "managed\n", detail)
        self.assertIn("qrcode — pairing QR renders", completed.stdout)
        self.assertNotIn("qrcode missing", completed.stdout)
        self.assertNotIn("Provisioning", completed.stdout)
        self.assertNotIn("Minting", completed.stdout)
        self.assertIn(str(self.home), completed.stdout)
        self.assertEqual((self.home / ".env").read_text(), "EXISTING=1\n")
        self.assertFalse((self.home / "psk").exists())
        self.assertEqual((self.home / "launcher-hits").read_text(), "1")
        self.assertEqual(completed.returncode, 1)
        self.assertNotIn("Traceback", completed.stderr)

    def test_reports_the_local_rest_api_only_when_something_answers(self):
        """The Agent tab's every RPC needs Hermes' local REST API, which lives
        outside the gateway — so a healthy chat proves nothing about it. The
        adapter starts one itself, so this line is advisory either way."""
        with socket.socket() as listener:
            listener.bind(("127.0.0.1", 0))
            listener.listen(1)
            live_port = listener.getsockname()[1]
            env = {"HERMES_BRIDGE_API_PORT": str(live_port)}
            self.assertEqual(pair.dashboard_port(env), live_port)

        # Same port, nothing listening now — and no fallback may rescue it.
        with patch.object(pair, "DASHBOARD_PORTS", ()):
            self.assertIsNone(pair.dashboard_port(env))

            report = pair.readiness_report(self.home, env)

        labels = [label for _, label, _ in report]
        self.assertTrue(
            any("local REST API" in label for label in labels),
            f"the readiness report must cover the dashboard: {labels}",
        )
        # WARN, not FAIL: pair.py runs before the gateway restart that starts
        # the API, so a missing one must not fail `--check` on a good pairing —
        # and must not print OK in front of a missing thing either.
        statuses = [s for s, label, _ in report if "local REST API" in label]
        self.assertEqual(statuses, [pair.WARN])
        self.assertTrue(pair.is_ready([(pair.WARN, "advisory", "")]))
        self.assertFalse(pair.is_ready([(pair.FAIL, "real", "")]))

    def test_second_run_repairs_without_reprovisioning(self):
        self._run()
        psk_before = (self.home / "psk").read_bytes()

        self._run()

        self.assertEqual(
            REQUESTS[1],
            {"profile_id": "profile_ss_abc123"},
            "a provisioned laptop must ask for an invite, not a new profile",
        )
        env_text = (self.home / ".env").read_text()
        self.assertEqual(env_text.count("HERMES_BRIDGE_API_KEY"), 1)
        self.assertEqual((self.home / "psk").read_bytes(), psk_before)

    def test_verbose_prints_all_pairing_data(self):
        output = StringIO()
        with redirect_stdout(output), patch.object(sys, "argv", ["pair.py", "--verbose"]):
            self._run()

        text = output.getvalue()
        psk = (self.home / "psk").read_bytes().hex()
        self.assertIn('"token": "tok_fresh"', text)
        self.assertIn("api_key: hb_secret", text)
        self.assertIn(f"psk: {psk}", text)
        self.assertIn(f'"token":"tok_fresh","psk":"{psk}"', text)
        self.assertIn("Pairing code: tok_fresh", text)


if __name__ == "__main__":
    unittest.main()
