"""
GENERATED by scripts/sync-from-expo-hermes.sh from expo-hermes's
plugins/platforms/hermes_bridge/test_streaming.py — edit the source there, not here.

Unit tests for HermesBridgeAdapter streaming (PRD_Features.md §2.2) —
send()'s expect_edits gate + edit_message().

Run:
    PYTHONPATH=<repo-root> ~/.hermes/hermes-agent/venv/bin/python plugins/platforms/hermes_bridge/test_streaming.py
or with any Python ≥3.8 that has websockets + PyNaCl installed.
"""

import os
import sys
import unittest
from unittest.mock import AsyncMock, MagicMock, patch

# Ensure repo root is on the path; testutil stubs heavy deps on import.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from testutil import PROFILE, PSK, make_adapter as _make_adapter
from hermes_bridge.crypto import open_frame


def _open(frame: str):
    payload = open_frame(PROFILE, "out", frame, PSK)
    assert payload is not None, "frame failed to decrypt"
    return payload


class _Closed(Exception):
    """Stand-in for websockets.exceptions.ConnectionClosed.

    testutil stubs the whole websockets package with a MagicMock, so the real
    name is not an exception class and cannot legally appear in an `except`
    clause. Patch adapter.ConnectionClosed with this to exercise a socket that
    drops mid-send."""


class TestSendExpectEdits(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.adapter = _make_adapter()

    async def test_normal_send_enqueues_durably(self):
        """No expect_edits metadata — today's exact behavior, unchanged."""
        sent_frames = []
        self.adapter._ws.send = AsyncMock(side_effect=lambda f: sent_frames.append(f))
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock()) as mock_enqueue:
            result = await self.adapter.send("chat-1", "hello")

        self.assertTrue(result.success)
        self.assertIsNotNone(result.message_id)
        mock_enqueue.assert_called_once_with(
            result.message_id, sent_frames[0], category="turn_complete"
        )
        payload = _open(sent_frames[0])
        self.assertEqual(payload["content"], "hello")
        self.assertNotIn("edit", payload)

    async def test_reply_frames_carry_phone_session_id_through_stream_finalize(self):
        sent_frames = []
        self.adapter._ws.send = AsyncMock(side_effect=lambda frame: sent_frames.append(frame))
        result = await self.adapter.send("chat-1", "Hel", reply_to="u1", metadata={"expect_edits": True, "thread_id": "phone-a"})
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock()):
            await self.adapter.edit_message("chat-1", result.message_id, "Hello", finalize=True)
        self.assertEqual(_open(sent_frames[0])["session_id"], "phone-a")
        self.assertEqual(_open(sent_frames[1])["session_id"], "phone-a")

    async def test_gateway_thread_is_stamped_as_phone_session_id(self):
        self.adapter._thread_phone_session["gateway-thread"] = "phone-session"
        sent_frames = []
        self.adapter._ws.send = AsyncMock(side_effect=lambda frame: sent_frames.append(frame))
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock()):
            await self.adapter.send("chat-1", "hello", metadata={"thread_id": "gateway-thread"})
        self.assertEqual(_open(sent_frames[0])["session_id"], "phone-session")

    async def test_inbound_event_remembers_phone_id_for_its_gateway_thread(self):
        with (
            patch.object(self.adapter, "_bridge_thread_id", AsyncMock(return_value="gateway-thread")),
            patch.object(self.adapter, "build_source", return_value=MagicMock(thread_id="gateway-thread")),
        ):
            await self.adapter._build_event({"session_id": "phone-session", "content": "hello", "msg_id": "u1"})
        self.assertEqual(self.adapter._thread_phone_session["gateway-thread"], "phone-session")
        self.assertEqual(self.adapter._message_session_id["u1"], "phone-session")

    async def test_inbound_event_stamps_valid_core_profile(self):
        from unittest.mock import MagicMock
        from hermes_bridge.bots_policy import ProfilesSnapshot
        with (
            patch.object(self.adapter, "_bridge_thread_id", AsyncMock(return_value="gateway-thread")),
            patch.object(self.adapter, "build_source", return_value=MagicMock(thread_id="gateway-thread")),
            patch("hermes_bridge.adapter.fetch_profiles_snapshot", AsyncMock(return_value=ProfilesSnapshot({}, None, [{"name": "work", "display_name": "Work", "is_default": False}]))),
            patch.dict(sys.modules, {"hermes_cli.gateway_multiplex_served": MagicMock(recorded_served_profiles=MagicMock(return_value=["work"]))}),
        ):
            event = await self.adapter._build_event({"session_id": "phone-session", "content": "hello", "core_profile": "work"})
        self.assertEqual(event.source.profile, "work")

    async def test_inbound_event_without_core_profile_keeps_source_unchanged(self):
        source = MagicMock(thread_id="gateway-thread")
        with patch.object(self.adapter, "_bridge_thread_id", AsyncMock(return_value="gateway-thread")), patch.object(self.adapter, "build_source", return_value=source):
            event = await self.adapter._build_event({"session_id": "phone-session", "content": "hello"})
        self.assertIs(event.source, source)

    async def test_unknown_profile_replies_without_running_turn(self):
        from hermes_bridge.bots_policy import ProfilesSnapshot
        with (
            patch.object(self.adapter, "_bridge_thread_id", AsyncMock(return_value="gateway-thread")),
            patch("hermes_bridge.adapter.fetch_profiles_snapshot", AsyncMock(return_value=ProfilesSnapshot({}, None, []))),
            patch.dict(sys.modules, {"hermes_cli.gateway_multiplex_served": MagicMock(recorded_served_profiles=MagicMock(return_value=[]))}),
            patch.object(self.adapter, "_deliver", AsyncMock()) as deliver,
        ):
            event = await self.adapter._build_event({"session_id": "phone-session", "content": "hello", "core_profile": "missing"})
        self.assertIsNone(event)
        self.assertEqual(deliver.await_args.args[1]["error_code"], "profile_not_served")

    async def test_unserved_profile_replies_without_running_turn(self):
        from hermes_bridge.bots_policy import ProfilesSnapshot
        with (
            patch.object(self.adapter, "_bridge_thread_id", AsyncMock(return_value="gateway-thread")),
            patch("hermes_bridge.adapter.fetch_profiles_snapshot", AsyncMock(return_value=ProfilesSnapshot({}, None, [{"name": "work"}]))),
            patch.dict(sys.modules, {"hermes_cli.gateway_multiplex_served": MagicMock(recorded_served_profiles=MagicMock(return_value=[]))}),
            patch.object(self.adapter, "_deliver", AsyncMock()) as deliver,
        ):
            event = await self.adapter._build_event({"session_id": "phone-session", "content": "hello", "core_profile": "work"})
        self.assertIsNone(event)
        self.assertEqual(deliver.await_args.args[1]["error_code"], "profile_not_served")

    async def test_snapshot_failure_replies_profiles_unavailable(self):
        with (
            patch.object(self.adapter, "_bridge_thread_id", AsyncMock(return_value="gateway-thread")),
            patch("hermes_bridge.adapter.fetch_profiles_snapshot", AsyncMock(side_effect=RuntimeError("offline"))),
            patch.object(self.adapter, "_deliver", AsyncMock()) as deliver,
        ):
            event = await self.adapter._build_event({"session_id": "phone-session", "content": "hello", "core_profile": "work"})
        self.assertIsNone(event)
        self.assertEqual(deliver.await_args.args[1]["error_code"], "profiles_unavailable")

    async def test_expect_edits_send_skips_durable_enqueue(self):
        """GatewayStreamConsumer's streaming-preview send() — must return a
        message_id (so the consumer knows we support editing) but must NOT
        durably enqueue the partial preview text."""
        sent_frames = []
        self.adapter._ws.send = AsyncMock(side_effect=lambda f: sent_frames.append(f))
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock()) as mock_enqueue:
            result = await self.adapter.send(
                "chat-1", "Hel", reply_to="phone-request-1", metadata={"expect_edits": True}
            )

        self.assertTrue(result.success)
        self.assertIsNotNone(result.message_id)
        mock_enqueue.assert_not_called()
        payload = _open(sent_frames[0])
        self.assertEqual(payload["content"], "Hel")
        self.assertTrue(payload["edit"], "the phone must classify the seed as a live preview")
        self.assertEqual(payload["reply_to"], "phone-request-1")

        with patch.object(self.adapter, "_enqueue_durable", AsyncMock()):
            await self.adapter.edit_message("chat-1", result.message_id, "Hello", finalize=True)
        final_payload = _open(sent_frames[1])
        self.assertEqual(final_payload["reply_to"], "phone-request-1")

    async def test_unsolicited_send_still_enqueues(self):
        """Cron/scheduled-job sends never set expect_edits — unaffected."""
        sent_frames = []
        self.adapter._ws.send = AsyncMock(side_effect=lambda f: sent_frames.append(f))
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock()) as mock_enqueue:
            result = await self.adapter.send(
                "chat-1", "job done", metadata={"job_id": "abc"}
            )

        self.assertTrue(result.success)
        mock_enqueue.assert_called_once_with(result.message_id, sent_frames[0], category=None)
        payload = _open(sent_frames[0])
        self.assertTrue(payload["unsolicited"])

    async def test_unsolicited_cron_send_seals_owning_profile(self):
        sent_frames = []
        self.adapter._ws.send = AsyncMock(side_effect=lambda frame: sent_frames.append(frame))
        with (
            patch.object(self.adapter, "_enqueue_durable", AsyncMock()),
            patch.object(
                self.adapter,
                "_rpc_cron_list",
                AsyncMock(return_value=[{"id": "abc", "profile": "coder"}]),
            ),
        ):
            await self.adapter.send("chat-1", "job done", metadata={"job_id": "abc"})

        payload = _open(sent_frames[0])
        self.assertTrue(payload["unsolicited"])
        self.assertEqual(payload["core_profile"], "coder")

    async def test_unsolicited_cron_send_omits_profile_when_lookup_fails(self):
        sent_frames = []
        self.adapter._ws.send = AsyncMock(side_effect=lambda frame: sent_frames.append(frame))
        with (
            patch.object(self.adapter, "_enqueue_durable", AsyncMock()),
            patch.object(self.adapter, "_rpc_cron_list", AsyncMock(side_effect=RuntimeError("offline"))),
        ):
            await self.adapter.send("chat-1", "job done", metadata={"job_id": "abc"})

        payload = _open(sent_frames[0])
        self.assertTrue(payload["unsolicited"])
        self.assertNotIn("core_profile", payload)

    async def test_unsolicited_cron_send_omits_profile_when_job_is_not_found(self):
        sent_frames = []
        self.adapter._ws.send = AsyncMock(side_effect=lambda frame: sent_frames.append(frame))
        with (
            patch.object(self.adapter, "_enqueue_durable", AsyncMock()),
            patch.object(self.adapter, "_rpc_cron_list", AsyncMock(return_value=[])),
        ):
            await self.adapter.send("chat-1", "job done", metadata={"job_id": "abc"})

        payload = _open(sent_frames[0])
        self.assertTrue(payload["unsolicited"])
        self.assertNotIn("core_profile", payload)


class TestEditMessage(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.adapter = _make_adapter()

    async def test_intermediate_edit_is_live_only(self):
        self.adapter._stream_pending.add("msg-abc")
        sent_frames = []
        self.adapter._ws.send = AsyncMock(side_effect=lambda f: sent_frames.append(f))
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock()) as mock_enqueue:
            result = await self.adapter.edit_message("chat-1", "msg-abc", "Hello wor")

        self.assertTrue(result.success)
        self.assertEqual(result.message_id, "msg-abc")
        mock_enqueue.assert_not_called()
        payload = _open(sent_frames[0])
        self.assertEqual(payload["msg_id"], "msg-abc")
        self.assertTrue(payload["edit"])
        self.assertNotIn("final", payload)
        self.assertEqual(payload["content"], "Hello wor")

    async def test_finalize_edit_enqueues_durably(self):
        self.adapter._stream_pending.add("msg-abc")
        sent_frames = []
        self.adapter._ws.send = AsyncMock(side_effect=lambda f: sent_frames.append(f))
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock()) as mock_enqueue:
            result = await self.adapter.edit_message(
                "chat-1", "msg-abc", "Hello world!", finalize=True
            )

        self.assertTrue(result.success)
        mock_enqueue.assert_called_once_with(
            "msg-abc", sent_frames[0], category="turn_complete"
        )
        payload = _open(sent_frames[0])
        self.assertTrue(payload["edit"])
        self.assertTrue(payload["final"])
        self.assertEqual(payload["content"], "Hello world!")

    async def test_edit_content_replaces_not_appends(self):
        """Each edit call carries the FULL accumulated text — verifies the
        adapter doesn't try to diff/append (that's the gateway's job)."""
        sent_frames = []
        self.adapter._stream_pending.add("msg-1")
        self.adapter._ws.send = AsyncMock(side_effect=lambda f: sent_frames.append(f))
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock()):
            await self.adapter.edit_message("chat-1", "msg-1", "Hi")
            await self.adapter.edit_message("chat-1", "msg-1", "Hi there")
            await self.adapter.edit_message("chat-1", "msg-1", "Hi there!", finalize=True)

        contents = [_open(f)["content"] for f in sent_frames]
        self.assertEqual(contents, ["Hi", "Hi there", "Hi there!"])

    async def test_edit_without_connection_fails(self):
        """An intermediate edit is live-only, so with no socket there is
        nothing to fall back on — and no socket delivery succeeds."""
        self.adapter._ws = None
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock(return_value=False)):
            result = await self.adapter.edit_message("chat-1", "msg-1", "text")
        self.assertFalse(result.success)
        self.assertEqual(result.error, "not_connected")

    async def test_finalize_without_connection_still_enqueues(self):
        """The terminal edit carries the real answer. Refusing outright on a
        dead socket — as this did — lost it with no durable row and no push."""
        self.adapter._ws = None
        self.adapter._stream_pending.add("msg-1")
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock(return_value=True)) as enq:
            result = await self.adapter.edit_message(
                "chat-1", "msg-1", "the whole answer", finalize=True
            )

        self.assertTrue(result.success, "durably queued means the phone will get it")
        self.assertFalse(result.retryable, "already queued — a retry would duplicate it")
        enq.assert_called_once()
        self.assertEqual(_open(enq.call_args[0][1])["content"], "the whole answer")

    async def test_completed_message_revisions_are_durable_unique_and_silent(self):
        sent_frames = []
        self.adapter._ws.send = AsyncMock(side_effect=lambda frame: sent_frames.append(frame))
        self.adapter._message_session_id["original"] = "phone-session"
        self.adapter._message_reply_to = {"original": "user-1"}
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock()) as enq:
            await self.adapter.edit_message("chat-1", "original", "first")
            await self.adapter.edit_message("chat-1", "original", "second")
        first, second = map(_open, sent_frames)
        self.assertEqual(first["msg_id"], "original#r1")
        self.assertEqual(second["msg_id"], "original#r2")
        self.assertEqual(second["replaces"], "original")
        self.assertEqual(second["reply_to"], "user-1")
        self.assertEqual(second["session_id"], "phone-session")
        self.assertEqual([call.kwargs["category"] for call in enq.call_args_list], [None, None])
        self.assertEqual(enq.call_count, 2)


class TestDeliveryWithoutALiveSocket(unittest.IsolatedAsyncioTestCase):
    """seal() needs no socket, so a frame can always be built and always be
    persisted. send()/edit_message()/_send_prompt() each used to refuse
    outright when _ws was None, dropping the message without ever queueing
    it."""

    def setUp(self):
        self.adapter = _make_adapter()

    async def test_send_without_connection_still_enqueues(self):
        self.adapter._ws = None
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock(return_value=True)) as enq:
            result = await self.adapter.send("chat-1", "hello")

        self.assertTrue(result.success)
        self.assertFalse(result.retryable)
        enq.assert_called_once()
        self.assertEqual(_open(enq.call_args[0][1])["content"], "hello")

    async def test_send_dropping_mid_flight_still_enqueues(self):
        """The socket was up at the top of send() and died during the write —
        the ConnectionClosed arm, not the no-socket arm."""
        self.adapter._ws.send = AsyncMock(side_effect=_Closed("gone"))
        with (
            patch("hermes_bridge.adapter.ConnectionClosed", _Closed),
            patch.object(self.adapter, "_enqueue_durable", AsyncMock(return_value=True)) as enq,
        ):
            result = await self.adapter.send("chat-1", "hello")

        self.assertTrue(result.success)
        enq.assert_called_once()

    async def test_prompt_without_connection_still_enqueues(self):
        self.adapter._ws = None
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock(return_value=True)) as enq:
            result = await self.adapter._send_prompt(
                "chat-1", "approval", "Approve?", [{"id": "yes", "label": "Yes"}], "p1"
            )

        self.assertTrue(result.success)
        enq.assert_called_once()
        payload = _open(enq.call_args[0][1])
        self.assertEqual(payload["role"], "prompt")
        self.assertEqual(payload["prompt_id"], "p1")

    async def test_enqueue_failure_with_dead_socket_reports_failure(self):
        """Neither path worked — this one really is undelivered, and the base
        class SHOULD retry it."""
        self.adapter._ws = None
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock(return_value=False)):
            result = await self.adapter.send("chat-1", "hello")

        self.assertFalse(result.success)
        self.assertTrue(result.retryable)
        self.assertEqual(result.error, "not_connected")

    async def test_live_send_ok_but_enqueue_failed_is_not_retryable(self):
        """A connected phone already has it. Only offline catch-up is lost, and
        a retry would show the message twice to everyone who is online."""
        with patch.object(self.adapter, "_enqueue_durable", AsyncMock(return_value=False)):
            result = await self.adapter.send("chat-1", "hello")

        self.assertTrue(result.success)
        self.assertFalse(result.retryable)


class TestStreamDiesBeforeFinalize(unittest.IsolatedAsyncioTestCase):
    """After ONE failed non-final edit, GatewayStreamConsumer never calls
    finalize on that message again: its non-flood failure branch
    (gateway/stream_consumer.py, "Edit failed ... entering fallback mode")
    sets _edit_supported=False and switches to a tail-only adapter.send().
    Making finalize durable therefore does not, on its own, save a stream that
    dies mid-flight — nothing would ever persist what already streamed."""

    def setUp(self):
        self.adapter = _make_adapter()
        self.enqueued = []

        async def fake_enqueue(msg_id, frame, category=None):
            self.enqueued.append((msg_id, frame, category))
            return True

        self.fake_enqueue = fake_enqueue

    async def _start_stream(self):
        preview = await self.adapter.send("chat-1", "Hel", metadata={"expect_edits": True})
        self.assertEqual(self.enqueued, [], "a preview must never be persisted")
        return preview.message_id

    async def test_failed_edit_persists_what_streamed_so_far(self):
        with patch.object(self.adapter, "_enqueue_durable", self.fake_enqueue):
            msg_id = await self._start_stream()
            self.adapter._ws = None  # socket dies mid-stream
            result = await self.adapter.edit_message("chat-1", msg_id, "Hello world so far")

        self.assertFalse(result.success, "the live edit genuinely failed")
        self.assertEqual(len(self.enqueued), 1)
        self.assertEqual(self.enqueued[0][0], msg_id)
        payload = _open(self.enqueued[0][1])
        # Edits carry the full replacement text, not a delta, so the content of
        # the edit that failed IS the complete answer to this point.
        self.assertEqual(payload["content"], "Hello world so far")
        self.assertTrue(payload["final"], "recovered frame must read as complete")

    async def test_flush_happens_exactly_once(self):
        """A later edit after the stream fallback is a durable revision."""
        with patch.object(self.adapter, "_enqueue_durable", self.fake_enqueue):
            msg_id = await self._start_stream()
            self.adapter._ws = None
            await self.adapter.edit_message("chat-1", msg_id, "first failure")
            await self.adapter.edit_message("chat-1", msg_id, "second failure")

        self.assertEqual(len(self.enqueued), 2)
        self.assertEqual(_open(self.enqueued[0][1])["content"], "first failure")
        self.assertEqual(_open(self.enqueued[1][1])["replaces"], msg_id)

    async def test_successful_finalize_leaves_nothing_to_flush(self):
        """The normal path: finalize lands, so a later stray failed edit for
        the same msg_id must not enqueue a second, older row."""
        with patch.object(self.adapter, "_enqueue_durable", self.fake_enqueue):
            msg_id = await self._start_stream()
            await self.adapter.edit_message("chat-1", msg_id, "all done", finalize=True)
            self.adapter._ws = None
            await self.adapter.edit_message("chat-1", msg_id, "stray late tick")

        self.assertEqual(len(self.enqueued), 2)
        self.assertEqual(_open(self.enqueued[0][1])["content"], "all done")
        self.assertEqual(_open(self.enqueued[1][1])["replaces"], msg_id)


if __name__ == "__main__":
    unittest.main()
