"""pair.py end-to-end against a stub relay: provision, then re-pair.
GENERATED by scripts/sync-from-expo-hermes.sh from expo-hermes's
plugins/platforms/hermes_bridge/test_pair.py — edit the source there, not here.


Runs the real script logic over a real HTTP server in a throwaway
HERMES_HOME — the two branches (fresh provision vs existing profile) differ
only by what is already in .env, which is exactly the state a mocked test
would have to fake.
"""

import json
import os
import socket
import sys
import tempfile
import threading
import unittest
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from unittest.mock import patch

import hermes_bridge.pair as pair

REQUESTS: list = []


class _StubRelay(BaseHTTPRequestHandler):
    def do_POST(self):  # noqa: N802 — BaseHTTPRequestHandler's naming
        body = json.loads(self.rfile.read(int(self.headers["Content-Length"])) or "{}")
        REQUESTS.append(body)
        if body.get("profile_id"):
            payload = {"profile_id": body["profile_id"], "token": "tok_repair"}
        else:
            payload = {
                "profile_id": "profile_ss_abc123",
                "api_key": "hb_secret",
                "token": "tok_fresh",
                "expires_at": "2026-01-01T00:00:00.000Z",
            }
        raw = json.dumps(payload).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def log_message(self, *_args):
        pass


class PairScriptTest(unittest.TestCase):
    def setUp(self):
        REQUESTS.clear()
        self.server = HTTPServer(("127.0.0.1", 0), _StubRelay)
        threading.Thread(target=self.server.serve_forever, daemon=True).start()
        self.addCleanup(self.server.shutdown)

        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.home = Path(self.tmp.name)
        (self.home / ".env").write_text("EXISTING=1\n")

        relay = f"http://127.0.0.1:{self.server.server_port}"
        self.env = patch.dict(os.environ, {"HERMES_HOME": str(self.home)})
        self.env.start()
        self.addCleanup(self.env.stop)
        # No tty in the test runner, so pair.py never prompts; seed the relay
        # the same way an existing install would.
        self.relay_ws = relay.replace("http:", "ws:")
        self.default_relay = patch.object(pair, "DEFAULT_RELAY", relay)
        self.default_relay.start()
        self.addCleanup(self.default_relay.stop)

    def _run(self):
        with patch.object(sys.stdin, "isatty", return_value=False):
            pair.main()

    def test_first_run_provisions_and_writes_credentials(self):
        self._run()

        env = pair.read_env(self.home / ".env")
        self.assertEqual(env["HERMES_BRIDGE_PROFILE_ID"], "profile_ss_abc123")
        self.assertEqual(env["HERMES_BRIDGE_API_KEY"], "hb_secret")
        self.assertEqual(env["HERMES_BRIDGE_RELAY_URL"], self.relay_ws)
        self.assertEqual(REQUESTS, [{}], "fresh install must not send a profile_id")

        psk = self.home / "psk"
        self.assertEqual(len(psk.read_bytes()), 32)
        self.assertEqual(psk.stat().st_mode & 0o777, 0o600)
        self.assertIn("EXISTING=1", (self.home / ".env").read_text())

    def test_authorizes_the_adapter_sender_with_hermes(self):
        """Without this, Hermes default-denies the phone's first message and
        answers with a pairing code instead of a reply."""
        self._run()

        env = pair.read_env(self.home / ".env")
        self.assertEqual(env["HERMES_BRIDGE_ALLOWED_USERS"], "mobile")

        # Re-running must not duplicate or clobber the entry.
        self._run()
        self.assertEqual(
            (self.home / ".env").read_text().count("HERMES_BRIDGE_ALLOWED_USERS"), 1
        )

    def test_sets_the_home_channel_to_the_profile_chat(self):
        """Unset, Hermes nags on the first message and cron has no target."""
        self._run()

        env = pair.read_env(self.home / ".env")
        self.assertEqual(env["HERMES_BRIDGE_HOME_CHANNEL"], "profile_ss_abc123")

        self._run()
        self.assertEqual(
            (self.home / ".env").read_text().count("HERMES_BRIDGE_HOME_CHANNEL"), 1
        )

    def test_leaves_an_operator_set_home_channel_alone(self):
        (self.home / ".env").write_text("HERMES_BRIDGE_HOME_CHANNEL=somewhere-else\n")

        self._run()

        env = pair.read_env(self.home / ".env")
        self.assertEqual(env["HERMES_BRIDGE_HOME_CHANNEL"], "somewhere-else")

    def test_leaves_an_operator_set_allowlist_alone(self):
        (self.home / ".env").write_text("HERMES_BRIDGE_ALLOWED_USERS=mobile,someone\n")

        self._run()

        env = pair.read_env(self.home / ".env")
        self.assertEqual(env["HERMES_BRIDGE_ALLOWED_USERS"], "mobile,someone")

    def test_check_flag_reports_without_minting_an_invite(self):
        """`--check` is the diagnose-an-existing-install path: no relay call."""
        with patch.object(sys, "argv", ["pair.py", "--check"]):
            with self.assertRaises(SystemExit) as caught:
                self._run()

        self.assertEqual(caught.exception.code, 1, "no allowlist yet — should fail")
        self.assertEqual(REQUESTS, [], "--check must not touch the relay")

    def test_readiness_fails_when_the_plugin_is_not_enabled(self):
        (self.home / "config.yaml").write_text("plugins:\n  enabled:\n    - something_else\n")
        self._run()  # pairs, and writes the allowlist

        def enablement_check():
            env = pair.read_env(self.home / ".env")
            return next(
                (ok for ok, label, _ in pair.readiness_report(self.home, env)
                 if "enabl" in label),
                None,
            )

        self.assertIs(enablement_check(), False)

        (self.home / "config.yaml").write_text("plugins:\n  enabled:\n    - hermes_bridge\n")
        self.assertIs(enablement_check(), True)

        # The inline-list form, and a legacy nested key, both count.
        (self.home / "config.yaml").write_text("plugins:\n  enabled: [other, hermes_bridge]\n")
        self.assertIs(enablement_check(), True)
        (self.home / "config.yaml").write_text(
            "plugins:\n  enabled:\n    - platforms/hermes_bridge\n"
        )
        self.assertIs(enablement_check(), True)

        # No config at all is "unknown", never a false alarm.
        (self.home / "config.yaml").unlink()
        self.assertIsNone(pair._plugin_enabled(self.home))

    def test_hands_itself_to_the_hermes_venv_interpreter(self):
        """qrcode lives in the Hermes venv, so a system python3 must not be the
        interpreter that reaches print_qr — see reexec_under_hermes_python."""
        venv_bin = self.home / "hermes-agent" / "venv" / "bin"
        venv_bin.mkdir(parents=True)
        venv_python = venv_bin / "python"
        venv_python.write_text("#!/bin/sh\n")
        venv_python.chmod(0o755)

        with patch.object(pair.os, "execv") as execv:
            self._run()
        self.assertEqual(execv.call_args[0][0], str(venv_python))

        # The guard flag it sets stops the re-exec'd process looping forever.
        with patch.object(pair.os, "execv") as execv:
            self._run()
        execv.assert_not_called()

    def test_reports_the_dashboard_api_only_when_something_answers(self):
        """The Agent tab's every RPC needs the local dashboard, which the
        gateway does not start — so a healthy chat proves nothing about it."""
        with socket.socket() as listener:
            listener.bind(("127.0.0.1", 0))
            listener.listen(1)
            live_port = listener.getsockname()[1]
            env = {"HERMES_BRIDGE_API_PORT": str(live_port)}
            self.assertEqual(pair.dashboard_port(env), live_port)

        # Same port, nothing listening now — and no fallback may rescue it.
        with patch.object(pair, "_API_PORTS", ()):
            self.assertIsNone(pair.dashboard_port(env))

            report = pair.readiness_report(self.home, env)

        labels = [label for _, label, _ in report]
        self.assertTrue(
            any("dashboard API" in label for label in labels),
            f"the readiness report must cover the dashboard: {labels}",
        )
        # Advisory only: pair.py runs before the operator starts the dashboard,
        # so a missing one must not fail `--check` on a healthy pairing.
        dashboard_ok = [ok for ok, label, _ in report if "dashboard API" in label]
        self.assertEqual(dashboard_ok, [True])

    def test_second_run_repairs_without_reprovisioning(self):
        self._run()
        psk_before = (self.home / "psk").read_bytes()

        self._run()

        self.assertEqual(
            REQUESTS[1],
            {"profile_id": "profile_ss_abc123"},
            "a provisioned laptop must ask for an invite, not a new profile",
        )
        env_text = (self.home / ".env").read_text()
        self.assertEqual(env_text.count("HERMES_BRIDGE_API_KEY"), 1)
        self.assertEqual((self.home / "psk").read_bytes(), psk_before)


if __name__ == "__main__":
    unittest.main()
