#!/usr/bin/env bash
# Sync hermes_bridge plugin source from the private monorepo (expo-hermes)
# into this public distribution repo.
#
# expo-hermes/plugins/platforms/hermes_bridge/ is where active development
# happens (adapter.py, crypto.py, tests). This repo is a public read-only
# mirror people `hermes plugins install` from. Left un-synced, it silently
# drifts (see: the "protocol mismatch" bug report that started this script —
# public plugin was months behind, missing attachments/voice/streaming/cron).
#
# This is a TRANSFORM sync, not a copy sync — the two repos use different
# import conventions (monorepo: `plugins.platforms.hermes_bridge.X`, package
# path 3 levels deep; public: `hermes_bridge.X`, tests/ 1 level deep) and the
# public repo owns some files outright (no source in the monorepo to sync
# from — see NEVER_SYNC below).
#
# Usage:
#   scripts/sync-from-expo-hermes.sh [path-to-expo-hermes-checkout]
# Default source path: ~/dev/react/expo-hermes
#
# Exits non-zero (and leaves the working tree with whatever partial changes
# were staged) if the public test suite fails after the transform — never
# publish a sync that doesn't pass its own tests.
set -euo pipefail

SRC_REPO="${1:-$HOME/dev/react/expo-hermes}"
SRC_PLUGIN="$SRC_REPO/plugins/platforms/hermes_bridge"
DST_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Fail on a missing tool now, not 90 seconds in after a clone and a venv
# build. CI runs this in python:3.12-slim, which is thinner than a dev box.
for tool in git find comm sort python3; do
  command -v "$tool" >/dev/null || {
    echo "ERROR: $tool is not installed — this script needs it."
    exit 1
  }
done

if [[ ! -d "$SRC_PLUGIN" ]]; then
  echo "ERROR: source plugin dir not found: $SRC_PLUGIN"
  echo "  Pass the expo-hermes checkout path as \$1 if it's not at ~/dev/react/expo-hermes."
  exit 1
fi

echo "Source: $SRC_PLUGIN"
echo "Dest:   $DST_REPO"
echo

# ---------------------------------------------------------------------------
# Bucket 1: pure copy (monorepo is source of truth, no path rewriting needed)
# ---------------------------------------------------------------------------
# Invariant this bucket depends on: these files must be free of monorepo-only
# import paths. If a future change to adapter.py/crypto.py starts importing
# `plugins.platforms.hermes_bridge...` (e.g. a relative import turned
# absolute), pure-copy would silently ship a broken file — so check, don't
# assume.
# Globbed, never hand-listed: adapter.py imports sibling modules, and a list
# goes stale silently — a new module (capability.py did exactly this) is simply
# never published and the plugin dies on import at the user's gateway.
PURE_COPY_FILES=(plugin.yaml after-install.md)
while IFS= read -r py; do
  PURE_COPY_FILES+=("$(basename "$py")")
done < <(find "$SRC_PLUGIN" -maxdepth 1 -name '*.py' \
  ! -name 'test_*' ! -name 'spike_*' ! -name 'testutil.py' | sort)

for f in "${PURE_COPY_FILES[@]}"; do
  if grep -q "plugins\.platforms\.hermes_bridge" "$SRC_PLUGIN/$f" 2>/dev/null; then
    echo "ERROR: $f contains a monorepo-only import path (plugins.platforms.hermes_bridge)."
    echo "  Pure-copy invariant broken — this file needs the same path rewrite"
    echo "  test files get (see bucket 2 below). Fix this script before syncing."
    exit 1
  fi
done

echo "Copying pure-copy files..."
for f in "${PURE_COPY_FILES[@]}"; do
  cp "$SRC_PLUGIN/$f" "$DST_REPO/hermes_bridge/$f"
  echo "  $f"
done
cp "$SRC_PLUGIN/requirements.txt" "$DST_REPO/requirements.txt"

# ---------------------------------------------------------------------------
# Bucket 2: copy + transform (tests that exercise adapter.py/crypto.py through
# the shared testutil.py harness)
# ---------------------------------------------------------------------------
# Transform order matters: the testutil rule must run BEFORE the general
# adapter/crypto rule, or `plugins.platforms.hermes_bridge.testutil` collapses
# to `hermes_bridge.testutil` (wrong — testutil.py is public-owned, bucket 3,
# a bare sibling-module import, not a hermes_bridge submodule).
TRANSFORM_FILES=(test_rpc.py test_streaming.py test_attachments.py test_pair.py)

transform() {
  local src="$1" dst="$2"
  {
    # First line of these files is always a `"""` docstring opener — insert
    # the generated-header notice as the second line so it survives inside
    # the existing docstring rather than needing its own comment block.
    head -n1 "$src"
    echo "GENERATED by scripts/sync-from-expo-hermes.sh from expo-hermes's"
    echo "plugins/platforms/hermes_bridge/$(basename "$src") — edit the source there, not here."
    echo
    tail -n +2 "$src" | sed \
      -e 's/plugins\.platforms\.hermes_bridge\.testutil/testutil/g' \
      -e 's/plugins\.platforms\.hermes_bridge\./hermes_bridge./g' \
      -e 's/os\.path\.join(os\.path\.dirname(__file__), "\.\.", "\.\.", "\.\.")/os.path.join(os.path.dirname(__file__), "..")/g'
  } > "$dst"
}

# The monorepo's test files sometimes import hermes_bridge.adapter/crypto
# BEFORE testutil (safe there — real Hermes core is installed, nothing needs
# stubbing). Here, testutil.py installs the gateway.platforms.base/tools.*
# stubs as an import side effect, so it MUST run before the first
# `hermes_bridge.*`/`gateway.*` import or that import fails with
# ModuleNotFoundError. Reorder rather than trust the source file's order.
reorder_testutil_first() {
  python3 - "$1" <<'PYEOF'
import re
import sys

path = sys.argv[1]
with open(path) as f:
    lines = f.readlines()

testutil_idx = next(
    (i for i, l in enumerate(lines) if re.match(r"^from testutil import", l)), None
)
first_hermes_idx = next(
    (i for i, l in enumerate(lines) if re.match(r"^from (hermes_bridge|gateway)\.", l)),
    None,
)
if (
    testutil_idx is not None
    and first_hermes_idx is not None
    and testutil_idx > first_hermes_idx
):
    line = lines.pop(testutil_idx)
    lines.insert(first_hermes_idx, line)
    with open(path, "w") as f:
        f.writelines(lines)
PYEOF
}

# Drift guard for the public-owned fixture: tests/testutil.py builds the
# adapter with __new__ and hand-sets its state, so a field added to the
# monorepo's make_adapter and missed here fails as an AttributeError inside
# whichever handler touches it first — long after the sync looked clean.
missing_fields="$(comm -23 \
  <(grep -oE '^\s+adapter\._[a-z_]+' "$SRC_PLUGIN/testutil.py" | tr -d ' ' | sort -u) \
  <(grep -oE '^\s+adapter\._[a-z_]+' "$DST_REPO/tests/testutil.py" | tr -d ' ' | sort -u))"
if [[ -n "$missing_fields" ]]; then
  echo "ERROR: tests/testutil.py's make_adapter is missing fields the monorepo sets:"
  echo "$missing_fields" | sed 's/^/  /'
  echo "  Add them to make_adapter in $DST_REPO/tests/testutil.py, then re-run."
  exit 1
fi

echo "Copying + transforming test files..."
for f in "${TRANSFORM_FILES[@]}"; do
  transform "$SRC_PLUGIN/$f" "$DST_REPO/tests/$f"
  reorder_testutil_first "$DST_REPO/tests/$f"
  echo "  $f"
done

echo
echo "NOTE: testutil.py, conftest.py, test_crypto.py, README.md are public-owned"
echo "(bucket 3) — never synced. See script header / their own docstrings for why"
echo "they diverge from the monorepo on purpose."
echo
echo "NOTE: this script does NOT scrub monorepo-internal doc references (issue"
echo "numbers, PRD section anchors) from copied comments — scrubbing would fork"
echo "the mirror's comments from their source. README.md's \"Reading the code"
echo "comments\" table is the legend instead; add any NEW issue number this sync"
echo "introduced to it."

# ---------------------------------------------------------------------------
# Correctness gate: refuse to leave a synced-but-broken repo. Never publish
# (commit/PR) past this point if it fails.
# ---------------------------------------------------------------------------
echo
echo "Running public test suite as the correctness gate..."
cd "$DST_REPO"
VENV="$DST_REPO/.sync-venv"
python3 -m venv "$VENV" >/dev/null
"$VENV/bin/pip" install -q -r requirements.txt pytest
"$VENV/bin/python" tests/test_crypto.py
"$VENV/bin/python" -m pytest tests/test_rpc.py tests/test_streaming.py tests/test_attachments.py tests/test_pair.py -q
rm -rf "$VENV"

# ---------------------------------------------------------------------------
# Install gate: `hermes plugins install` security-scans the tree it is about to
# install and refuses a caution verdict without --force (a dangerous verdict
# cannot be forced at all). It scans ONLY hermes_bridge/ (we publish with
# `subdir: hermes_bridge`), which is why README/install prose and test fixtures
# must stay out of that directory. Plugin doctor runs the real manifest +
# registration contracts. Skipped when Hermes isn't installed here.
# ---------------------------------------------------------------------------
HERMES_AGENT="${HERMES_HOME:-$HOME/.hermes}/hermes-agent"
if [[ -x "$HERMES_AGENT/venv/bin/python" ]]; then
  echo
  echo "Running the Hermes install scan + plugin doctor on hermes_bridge/..."
  (cd "$HERMES_AGENT" && ./venv/bin/python - "$DST_REPO/hermes_bridge" <<'PYEOF'
import sys
from pathlib import Path

from hermes_cli.plugin_dev import doctor_plugin
from tools.plugin_guard import format_scan_report, scan_plugin, should_allow_plugin_install

target = Path(sys.argv[1])

scan = scan_plugin(target, source="community")
allowed, reason = should_allow_plugin_install(scan)
print(format_scan_report(scan))
print(f"  install decision: {reason}")

report = doctor_plugin(target)
print(report.format_text())

if allowed is not True or not report.ok:
    print("\nFAILED: this tree would not install cleanly. Fix before publishing.")
    sys.exit(1)
PYEOF
  )
else
  echo
  echo "WARNING: no Hermes install at $HERMES_AGENT — skipped the install scan and"
  echo "plugin doctor. Run them before publishing."
fi

echo
echo "Sync complete and verified. Review the diff, then commit:"
echo "  git -C '$DST_REPO' status --short"
echo "  git -C '$DST_REPO' diff"
